xkbcommon/libxkbcommon

- src/context.c
Trivial patch that allows overriding the DFLT_XKB_CONFIG_ROOT path via a new XKB_CONFIG_ROOT environment to make it possible to set the path at runtime instead of build-time (to make  binaries build with libxkbcommon easier relocatable).
> Add XKB_CONFIG_ROOT environment

- Makefile.am
- bench/bench.c
- bench/bench.h
- bench/compose.c
- bench/key-proc.c
- bench/rules.c
- configure.ac
- test/x11comp.c
This series of patches consists of two commits.
Although each of the commits may be handled independently, I'm placing them in a single PR because I think they are closely related in terms of the `make check` test on a specific platform, as suggested in the title.
On Mac OS X, the `make check` test cannot be carried out because
(1) Since `clock_gettime()` is not available on the OS, all the programs `bench/*.c` won't compile.
(2) When XQuartz's `Xvfb` is given the option `-displayfd`, it is observed that it always returns `:0`.   As a consequence, `x11comp` uses that (default) display number to connect to the X server and closes it when it's finished.  Obviously, that leaves the window system in an undesirable state.
Commit 4627892 handles the first issue and Commit 18e6612 the second. …
> Modifications to make 'make check' test complete for Mac OS X

- .travis.yml
- Makefile.am
- doc/Doxyfile.in
Instead of giving Doxygen a series of absolute paths to the source
files and a relative path to the output directory, run it from the
source directory with purely relative paths to the source files, and
give it an absolute path to the build directory.
This fixes the parsing of README.md with a separate build directory,
since the relative includes for doc/quick-guide.md and doc/compat.md
don't resolve otherwise. Doxygen's INCLUDE_PATH turns out not to fix
this either, since that's just a set of paths to open and parse, rather
than an analogue to cpp's -I.
Signed-off-by: Daniel Stone <daniels@collabora.com>
> doc: Fix Doxygen include for srcdir != builddir

- .travis.yml
Looks like the CI machines were updated to use Ubuntu 14.04, which has
libxcb 1.10, which is new enough. Lets see if it works.
Signed-off-by: Ran Benita <ran234@gmail.com>
> travis: remove --disable-x11

- src/ks_tables.h
- xkbcommon/xkbcommon-keysyms.h
xproto recently has been extended with 4 new keysyms:
XF86XK_Keyboard
XF86XK_WWAN
XF86XK_RFKill
XF86XK_AudioPreset
This commit is the result of running "make update-keysyms" on a system
with the updated xproto installed.
Signed-off-by: Hans de Goede <hdegoede@redhat.com>
> Sync Keysyms with recent xproto additions

- src/keysym-utf.c
While working on a custom keyboard layout, I noticed that the `permille` keysym was not being translated to the U+2030 (PER MILLE SIGN) character. Evidently this keysym was omitted from `keysymtab`, presumably by mistake. It is even absent from the original [keysym2ucs](http://www.cl.cam.ac.uk/~mgk25/ucs/keysym2ucs.c) table from which xkbcommon's `keysym-utf.c` is derived.
This pull request adds the missing `permille` table entry and also fills in the placeholder for `signifblank` U+2423 (OPEN BOX).
> keysym-utf: Add missing codes for signifblank and permille keysyms

- meson.build
Old meson expects an array with one dependency per element. Providing a
string containing multiple deps results in only the first dep getting
its whitespace properly applied. As a result, the output was:
Requires.private: xcb >= 1.10 xcb-xkb>=1.10
And downstream projects failed to find a package named 'xcb-xkb>=1.10'.
Specifying an array of versioned deps results in correct output:
Requires.private: xcb >= 1.10, xcb-xkb >= 1.10
Fixes #64.
> meson: Fix xkbcommon-x11.pc Requires versioning

- Makefile.am
- meson.build
- test/.gitignore
- test/common.c
- test/print-compiled-keymap.c
- test/rmlvo-to-keymap.c
- test/xkeyboard-config-test.py.in
I'm mostly looking for feedback right now, this doesn't have to be merged.
This started as a way to figure out how to test xkeyboard-config in some automated way. The easiest/most basic thing is to test all the combinations at least compile into a keymap. And that's what this does - the first commit introduces a tool to compile RMLVO into a keymap, the second tool uses xkeyboard-config's `evdev.xml` file to generate the various combinations and runs them through the tool. Ideally, this way we can at least spot when there's something off with the compilation.
Arguably more an xk-c tool but if the compilation fails for some reason it could also be in xkbcommon.
Feedback appreciated, thanks.
> xkeyboard-config combination tester

- xkbcommon/xkbcommon-keysyms.h
> keysyms: fix comment for XKB_KEY_OCARON

- meson.build
This works around meson bug 3937, 'link_whole' arguments don't get added into
the final static library and we end up with a virtually empty 8-byte
libxkbcommon.a file, see https://github.com/mesonbuild/meson/issues/3937
Workaround is simply to add all sources to both libraries we need them in.
This obviously compiles them twice but this year's winter was cold and
bit of extra warmth will be appreciated.
Fixes #84
> meson.build: manually link all sources into the library

- meson.build
We can't always execute binaries from the host or target machine,
as is the case in cross compilation.
This instead uses native : true to search the build system for wayland-scanner.pc and get it from there.
Fixes cross compilation on Void Linux
Side-note: Meson is so nice and makes this so trivially easy.
> meson.build: use program from build machine not host or target.

- Makefile.am
With older versions of autotools, one needs to add this line to
Makefile.am. From the autoconf docs: "Note that if you use aclocal from
Automake to generate aclocal.m4, you must also set ACLOCAL_AMFLAGS = -I dir
in your top-level Makefile.am". [1]
I couldn't build with autoconf 2.68 without this.
[1] https://www.gnu.org/software/autoconf/manual/autoconf-2.65/html_node/Input.html
Signed-off-by: milloni <milloni@preemptable.org>
> Makefile.am: add include dir for AC_CONFIG_MACRO_DIR to work

- configure.ac
- meson.build
- src/state.c
- src/utils.h
We don't need to determine the total number of bits set to determine if
at most one is set.
Additionally, on x86_64 without any -march=* flag, __builtin_popcount
will get compiled to a function call to the compiler runtime (on gcc),
or a long sequence of bit operations (on clang).
> Use bitwise test for power-of-2 instead of popcount

- Makefile.am
- configure.ac
- meson.build
- test/interactive-wayland.c
xdg_shell v6 was pretty close to the finalised stable version of
xdg-shell. We can now just use the stable version, which is supported
everywhere (Enlightenment, KWin, Mutter, Weston, wlroots).
This requires bumping the wayland-protocols dependency.
Signed-off-by: Daniel Stone <daniels@collabora.com>
> interactive-wayland: Port to stable xdg-shell

- test/rmlvo-to-keymap.c
The demo program "rmlvo-to-keymap" can't
compile on darwin.
This is because `program_invocation_short_name` has portability issues.
This broke the build on darwin in nixpkgs https://github.com/NixOS/nixpkgs/pull/65010
> test/rmlvo-to-keymap.c: use basename to get program name

- .azure-pipelines/steps/autotools.yml
- .azure-pipelines/steps/dependencies-linux.yml
- .azure-pipelines/steps/dependencies-macos.yml
- .azure-pipelines/steps/meson.yml
- azure-pipelines.yml
- scripts/meson-junit-report.py
As requested by @bluetech in #103 I have been investigating on using Azure Pipelines for the continuous integration, and it looks like I more or less have been able to replicate what Travis is currently doing:
- Building on Ubuntu:
- Clang+Autotools
- Clang+Meson+Valgrind
- GCC+Autotools
- GCC+Meson+Valgrind
- Building on Mac OS:
- Clang+Meson
The only differences with the current Travis configuration are:
- The most recent Ubuntu version Azure has is Xenial, so I had to pass `-Denable-wayland=false` for the Meson builds because the Wayland development packages are too old.
- Mac OS gets an update from 10.2 to 10.13
- Output from the tests is gathered from Meson's JSON log files an converted to JUnit XML, which Azure can ingest to show the test results in the Web interface.
Note that I …
> CI: Use the Azure Pipelines service

- meson.build
Fix meson build on Solaris by using __EXTENSIONS__ where Linux & other
platforms use _GNU_SOURCE.  Without this the build fails due to missing
prototypes for functions like strdup & getopt not defined in the C99
standard.  (In autoconf, this was handled by AC_USE_SYSTEM_EXTENSIONS.)
Signed-off-by: Alan Coopersmith <alan.coopersmith@oracle.com>
> build: Solaris needs __EXTENSIONS__ instead of _GNU_SOURCE

- src/context.c
- test/context.c
Use $XDG_CONFIG_HOME/xkb as the primary lookup path for XKB rules. Same
motivation as in 3a91788d9254b, however the XDG directories are more standard
and recommended these days than application-specific dotfiles.
The XDG spec says to fall back to $HOME/.config where XDG_CONFIG_HOME is not
set so we implement that behavior as well.
Fixes #112
> Use XDG_CONFIG_HOME as first XKB search path

- scripts/makeheader
with X11_HEADERS_PREFIX
Signed-off-by: Sebastian Wick <sebastian@sebastianwick.net>
> scripts/makeheader: allow overriding the prefix path of the X11 headers

- test/xkeyboard-config-test.py.in
Unscientific measurement: improvement by ~14 min down to ~8 min, depending on processor count etc.
Instead of a single thread, run this across a `multiprocessing.Pool()` with the side-effect that it also forces us to collate the output which in turn allows us to split that output between stdout and stderr for success/failures.
> Speed up xkeyboard config test

- test/xkeyboard-config-test.py.in
python3 is always python3, but python could be python2 in some cases. Or just
missing (e.g. RHEL8).
I don't think there's any distro where `python` is available (and is python3) but the `python3` command isn't.
> test: xkeyboard-config: invoke the python3 command

- test/common.c
Coverity actually complains about a few others but many of those are false positives. And others are largely in the test code - these two are the only ones that I could justify writing a patch for (i.e. where it doesn't get more convoluted afterwards). And IMO only the memleak patch is really one that's worth merging.
> two coverity fixes

- xkbcommon/xkbcommon.h
Missing from e23f1061b2b9c8d40ba7797a5ffbd6d474d604e0 and
3a91788d9254b4571ff883439931f497d8a0663f.
> docs: update the include path documentation

- test/rmlvo-to-kccgst.c
The short options were left for backwards compatibility.
> test: let rmlvo-to-kccgst take long options like rmlvo-to-keymap

- src/keysym.c
lowercase: LATIN SMALL LETTER SHARP S (U+00DF)
uppercase: LATIN CAPITAL LETTER SHARP S (U+1E9E)
The uppercase sharp s (XK_ssharp) is a relatively recent addition to unicode
but was added to the relevant keyboard layouts in xkeyboard-config-2.25
(d1411e5e95c)
https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/issues/144
Alas, the CapsLock behavior was broken on the finnish layout (maybe others).
This was due XConvertCase() never returning the uppercase characters.
Let's make this function return the right lower/upper symbols for the sharp s
and hope that the world won't get any worse because of it.
Corresponding Xlib issue:
https://gitlab.freedesktop.org/xorg/lib/libx11/issues/110
> keysym: handle ssharp in XConvertCase()

- meson.build
- src/context.c
- src/context.h
- src/xkbcomp/rules.c
- test/data/rules/inc-dst-loop-twice
- test/data/rules/inc-dst-simple
- test/data/rules/inc-src-before-after
- test/data/rules/inc-src-loop-twice
- test/data/rules/inc-src-looped
- test/data/rules/inc-src-nested
- test/data/rules/inc-src-options
- test/data/rules/inc-src-simple
- test/rules-file-includes.c
This adds an `! include /path/to/rulesfile` directive for rules files. The simplest case would be to ship `xkeyboard-config` with an extra line at the end in the form of:
```
! include %h/.xkb/rules/myrules
```
Then that file can contain something like this:
```
! option      = symbols
custom:foo  = +custom(foo)
```
and resolve accordingly. This allows for simple additions of local configurations without having to modify the parsers too much. Conveniently, `xkbcomp` ignores the `! include` directive though this is still an API break for the rules files so distributions need to figure out what to do here. We do need to get this into xkbcomp/libxkbfile too though to have the same behaviour for wayland and xorg.
The directive is simple and currently only allows for `%h` to resolve to …
> Allow for custom rulesets through include files.

- src/keysym-utf.c
- test/keysym.c
- xkbcommon.map
- xkbcommon/xkbcommon.h
In order to support features like auto-type and UI automation, the
relevant tools need to be able to invert the keycode->keysym->text
transformation. In order to facilitate that, a new API was added.
It allows querying the keysyms that correspond to particular Unicode
codepoints. For all practical purposes, it can be thought of as an
inverse of xkb_keysym_to_utf32().
> Support translation Unicode codepoints to keysyms

- src/keymap.c
- src/keymap.h
- src/state.c
- test/keymap.c
- xkbcommon.map
- xkbcommon/xkbcommon.h
The new API is useful to implement features like auto-type and
desktop automation. Since the inputs for these features is usually
specified in terms of the symbols that need to be typed, the
implementation needs to be able to invert the keycode->keysym->text
transformation and produce a sequence of keycodes that can be used
to type the requested character(s).
> A new API to query modifier set required to type a keysym

- meson.build
- test/how-to-type.c
- xkbcommon/xkbcommon.h
The program takes a unicode codepoint and an RMLVO and prints out all
key + modifier combinations that would result in that codepoint.
The program was written to exercise the new
xkb_keymap_key_get_mods_for_level() function. It's handy and can be
extended in several ways, but enough for now.
Example:
$ ./build/how-to-type -l us,il,ru 0x41 | column -ts $'\t'
keysym: A (0x41)
KEYCODE  KEY NAME  LAYOUT#  LAYOUT NAME   LEVEL#  MODIFIERS
38       AC01      1        English (US)  2       [ Shift ]
38       AC01      1        English (US)  2       [ Lock ]
38       AC01      2        Hebrew        2       [ Shift ]
38       AC01      2        Hebrew        2       [ Lock ]
$ ./build/how-to-type -l de -v neo 0x3b6 | column -ts $'\t'
keysym: Greek_zeta (0x7e6)
KEYCODE  KEY NAME  LAYOUT#  LAYOUT …
>  test: add "how to type" demo program 

- meson.build
Link libxkbcommon_x11_internal with libxkbcommon_test_internal, rather
than libxkbcommon.
This avoids some tests linking with both libxkbcommon_test_internal and
libxkbcommon, which causes duplicate symbol problems on PE targets (e.g.
Cygwin) (as all the symbols from libxkbcommon are pulled in at link
time, which clash with libxkbcommon_test_internal)
> Fix building X11 tests on PE targets

- src/keymap.c
- test/keymap.c
Fixes https://github.com/xkbcommon/libxkbcommon/issues/140.
If the active set of modifiers doesn't match any explicit entry of the
key type, the resulting level is 0 (i.e. Level 1). Some key types don't
explicitly map Level 1, taking advantage of this fallback.
Previously, xkb_keymap_key_get_mods_for_level didn't consider this, and
only reported masks for explicit mappings. But this causes some glaring
omissions, like matching "a" in the "us" keymap returning not results.
Since every mask which isn't explicitly mapped falls back to 0, we can't
return the all. Almost always the best choice for this is the empty
mask, so return that, when applicable.
> keymap: don't forget about fallback mappings in xkb_keymap_key_get_mods_for_level()

- doc/user-configuration.md
XKB_CONFIG_ROOT (if defined) replaces the built-in system directories.
Fixes 5fb2c6769b7259ba647781bc800d6a46d90cf1a9
> doc: correct the include path list

- test/xkeyboard-config-test.py.in
Regression introduced in 362130debb5d90d77f0d4f7549880b5f9699f647
> test: fix the xkeyboard-config test for the prefixed tool name

- src/compose/paths.c
- src/context.c
- src/registry.c
- src/utils.h
- src/xkbcomp/include.c
- test/common.c
- test/compose.c
- test/context.c
- test/registry.c
Return the allocated string or NULL which is a much better interface than the `asprintf` "return length or -1 and the string pointer is undefined". And use that in xkbcomp's include buffer handling because there's no real need for realloc here.
Edit: this is split out from #162
> Add the (v)asprintf_safe helper function

- meson.build
../meson.build:239: DEPRECATION: Library xkbcommon was passed to the "libraries"
keyword argument of a previous call to generate() method instead of first
positional argument. Adding xkbcommon to "Requires" field, but this is a
deprecated behaviour that will change in a future version of Meson. Please
report the issue if this warning cannot be avoided in your case.
This was introduced in meson 0.49.0
Note: meson 0.49 was released in December 2018. Feel free to leave this one sitting until we're happy to require a newer meson version.
> meson.build: fix pkgconfig deprecation warning

- src/compose/paths.c
- src/compose/paths.h
- src/compose/table.c
- xkbcommon/xkbcommon-compose.h
Before reading `~/.XCompose`, try to read `$XDG_CONFIG_HOME/XCompose` (falling back to `~/.config/XCompose`).
This helps unclutter the home directory of users who want that.
> Add xdg base directory support to Compose

- test/tool-option-parsing.py
Let's not have our tests fail if the user has an incompatible `$XDG_CONFIG_HOME/xkb` directory.
libxkbcommon has fallbacks when XDG_CONFIG_HOME isn't set so we need to override this with a real directory instead of just unsetting it.
But how can this happen? Well, for example if you're trying to run the test suite on git master when you already have a xkb directory for #162 :)
> test: ignore the real XDG_CONFIG_HOME during tests

- test/xkeyboard-config-test.py.in
`xkbcli compile-keymap` doesn't work unless we ninja install first. But for a
test that's to be run from the test directory, that's not a useful option so
let's call the binary directly. The script adds the meson builddir to the PATH
anyway.
> test: fix the xkeyboard-config test

- tools/xkbcli-compile-keymap.1
- tools/xkbcli-how-to-type.1
- tools/xkbcli-interactive-evdev.1
- tools/xkbcli-interactive-wayland.1
- tools/xkbcli-interactive-x11.1
- tools/xkbcli-list.1
- tools/xkbcli.1
The mdoc is more semantic and consistent.
> tools: convert man pages from man format to mdoc format

- meson.build
- tools/tools-common.c
PATH_MAX not POSIX and can be missing on some systems, notably Windows (which
provides MAX_PATH instead tough) and Hurd. Let's define it to a sane value where
missing, i.e.  the one it's defined as in limits.h
Fixes https://github.com/xkbcommon/libxkbcommon/issues/180
> meson.build: define PATH_MAX where it's missing

- xkbcommon/xkbcommon.h
Add a clarifying note about "short" layout names to the docs, as suggested by @bam80.
Fixes: https://github.com/xkbcommon/libxkbcommon/issues/193
> doc: add note about "short" layout names

- src/xkbcomp/parser.y
- test/data/symbols/garbage
- test/keymap.c
Where resolve_keysym fails we warn but use the otherwise uninitialized variable
as our keysym. That later ends up in the keymap as random garbage hex value.
Simplest test case, set this in the 'us' keymap:
```
key <TLDE>               {      [        xyz ] };
```
And without this patch we get random garbage:
```
./build/xkbcli-compile-keymap --layout us | grep TLDE:
key <TLDE>               {      [      0x018a5cf0 ] };
```
With this patch, we now get NoSymbol:
```
./build/xkbcli-compile-keymap --layout us | grep TLDE:
key <TLDE>               {      [        NoSymbol ] };
```
> xkbcomp: where a keysym cannot be resolved, set it to NoSymbol

- test/xkeyboard-config-test.py.in
Prompted by
https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/merge_requests/127
We run the keymap tool with `--verbose` which will print the messages from the
compiler to the log file as well. And then we can search for the warning
regarding an unrecognized keysym and fail our test based on that.
cc @svu
> test: catch unrecognized keysyms in the xkeyboard-config test

- bench/x11.c
- meson.build
- src/context.c
- src/context.h
- src/x11/util.c
On every keymap notify event, the keymap should be refreshed, which fetches the required X11 atoms. A big keymap might have a few hundred of atoms.
A [profile by a user](https://github.com/i3/i3/issues/3924#issuecomment-729890732) has shown this *might* be slow when some intensive amount of keymap activity is occurring. It might also be slow on a remote X server.
While I'm not really sure this is the actual bottleneck, caching the atoms is easy enough and only needs a couple kb of memory, so do that.
On the added bench-x11:
```
Before: retrieved 2500 keymaps from X in 11.233237s
After : retrieved 2500 keymaps from X in 1.592339s
```
> x11: cache X11 atoms

- doc/keymap-format-text-v1.md
Fixes #198 
I apologise in advance for the grammatical mistakes, English is not my main language. I took the content from [An Unreliable Guide to XKB Configuration][1] and reworded most of it.
[1]: https://www.charvolant.org/doug/xkb/
> doc/keymap: add documentation for xkb_symbols

- test/tool-option-parsing.py
Just a typo. whoops.
Together with a change to make this test easier to run from the git tree.
Fixes #206
> Fix failing evdev-interactive test cases

- src/x11/keymap.c
- src/x11/util.c
- src/x11/x11-priv.h
This is my attempt at fixing #216.
As written there, before this PR I got this output and saw 78 round trips just for `xkb_x11_keymap_new_from_device`:
```
Needed 0.104062 for xcb_connect()
Needed 0.201753 for xkb_x11_setup_xkb_extension()
Needed 0.100868 for xkb_x11_get_core_keyboard_device_id()
Needed 7.851895 for xkb_x11_keymap_new_from_device()
Needed 0.100844 for xkb_x11_state_new_from_device()
Needed 0.003317 for xkb_keymap_get_as_string()
Needed 0.000224 for cleanup()
```
With this PR, my output is (and there are only three round trips for `new_from_device`):
```
Needed 0.104250 for xcb_connect()
Needed 0.201609 for xkb_x11_setup_xkb_extension()
Needed 0.100910 for xkb_x11_get_core_keyboard_device_id()
Needed 0.348044 for xkb_x11_keymap_new_from_device()
Needed 0.100926 for …
```
> Reduce number of X11 round trips

- tools/interactive-evdev.c
- tools/xkbcli-interactive-evdev.1
- tools/xkbcli.1
- tools/xkbcli.c
Turns out FreeBSD supports evdev, so this toll can work on it; however
it does not support epoll, so switch to poll, which is portable.
Reported-by: Evgeniy Khramtsov <evgeniy@khramtsov.org>
> interactive-evdev: switch from epoll(2) to poll(2)

- src/xkbcomp/action.c
The target buffer is 7 bytes long, null-termination is optional (as the comment
already suggests). Coverity is unhappy about this though so let's use memcpy
instead, it does the same thing here.
> xkbcomp: use memcpy over strncpy to avoid analyzer warnings

- src/compose/parser.c
- src/compose/state.c
- src/compose/table.c
- src/compose/table.h
Previously we used a simple trie with a linked list for each chain.
Unfortunately most compose files have very long chains which means the
constructions performs an almost quadratic number of comparisons.
Switch to using a ternary search tree instead. This is very similar to a
trie, only the linked list is essentially replaced with a binary tree.
On the en_US/Compose file, the perf diff is the following (the modified
function is `parse`):
Event 'cycles:u'
Baseline  Delta Abs  Shared Object     Symbol
........  .........  ................  .................................
39.91%    -17.62%  bench-compose     [.] parse.constprop.0
20.54%     +6.47%  bench-compose     [.] lex
17.28%     +5.55%  libc-2.33.so      [.] __strcmp_avx2
12.78%     +4.01%  bench-compose     [.] xkb_keysym_from_name …
> compose: use a ternary tree instead of a regular trie

- src/x11/util.c
The numpad:mac option doesn't specify a name for the first level:
// On Mac keypads, level 1 and 2 are swapped.
partial xkb_types "mac" {
type "KEYPAD" {
modifiers = None;
map[None] = Level2;
level_name[Level2] = "Number";
};
include "extra(keypad)"
};
This means the atom for level name is XCB_ATOM_NONE. We tried to get its
name, which fails. This regressed in 40c00b472144d1684d2fb97cafef39.
Instead, translate it to XKB_ATOM_NONE, same as the previous behavior.
Fixes: https://github.com/xkbcommon/libxkbcommon/issues/229
> x11: fix xkb_x11_keymap_new_from_device failing when a level name is empty

- doc/user-configuration.md
Support copy-pasting from the docs to get something functional.
Parsing errors may end up in the journal, where they are not super easy to find.
> doc: fix user-configuration sample file

- test/xkeyboard-config-test.py.in
We're compiling something like 80k layout combinations in the xkeyboard-config CI with this tool, producing a 6+ GB output file that we then have to grep through to find the actual error. That is ... not very productive.
Let's switch to this tool printing out YAML format so we can use `yq` or other scripts to search for the data we want.
An example MR for how the results then look like is here: https://gitlab.freedesktop.org/whot/xkeyboard-config/-/merge_requests/1, just click on the "Expand" button once the test results are parsed and it nicely shows which ones break.
cc @svu
> test: let the keyboard layout tester produce YAML as output format

- src/keysym.c
- test/keysym.c
This is hit when passing an empty string and XKB_KEYSYM_CASE_INSENSITIVE
currently, causing the array access into name_to_keysym to be out of
bounds on the next iteration of the loop.
Fixes #237
> keysym: fix underflow in xkb_keysym_from_name

- tools/registry-list.c
We have a lot of keyboard layouts and the current output format is virtually
useless at searching for a specific one to debug any issues with either the
layout list or the output from libxkbregistry.
Let's use YAML instead because that can easily be post-processed to extract the
specific layouts wanted, e.g. to get the list of all layouts:
`xkbcli-list | yq -r ".layouts[].layout"`
to get the list of all variants of the "us" layout:
`xkbcli-list | yq -r '.layouts[] | select(.layout == "us") | .variant`
and the number of option groups:
`xkbcli-list | yq -r '.option_groups[] | length'`
Note that the top-level nodes have been de-capitalized, so where it was "Models"
before it is now "models" and the "Options" node is now "option_groups".
**Note:** this is a breaking change, but I'm not sure …
> change the xkbcli list output to YAML

- meson.build
- scripts/map-to-def
Arrange for passing `.def` files with the lists of symbols to export from DLLs when building on Windows with MSVC. Without this no symbols were being exported at all.
> Windows: Pass list of symbols to export to MSVC

- meson.build
Specify where to find the headers for `libxkbcommon_dep`, which allows other projects to correctly locate the headers when `libxkbcommon` is being built as a Meson subproject.
> Meson: Allow building as subproject

- bench/atom.c
- meson.build
- src/atom.c
While the previous 1987-style[0] scheme was fun (and I reasonably
optimized it for a fair comparison), this task is more suited to a hash
table. Even a simple implementation beats the old one.
[0] Seems to have first appeared in X11R1, released September 1987.
See server/dix/atom.c here: https://www.x.org/releases/X11R1/X.V11R1.tar.gz
> atom: rewrite as a hash table

- tools/interactive-x11.c
Don't assume that keycode 9 means Escape. Instead, use the keymap
to check for Esc.
Logic copied from the Wayland version.
Signed-off-by: Simon Ser <contact@emersion.fr>
> tools/interactive-x11: use keysym to look for Esc

- tools/registry-list.c
Because otherwise the 'no' layout is treated as disagreement with whatever is to
be disagreed with. Fixed in YAML 1.2 but that's not universally supported.
Fixes #268
> tools: enclose the layout name in quotes

- src/registry.c
From the documentation:
> It does not clean up parser state, it cleans up memory allocated by the library
> itself. It is a cleanup function for the XML library. It tries to reclaim all
> related global memory allocated for the library processing. [...]
> One should call xmlCleanupParser() only when the process has finished using the library.
http://xmlsoft.org/html/libxml-parser.html#xmlCleanupParser
Since we're a library ourselves we cannot know if something else in the same
proces uses the parser, so we must not call this.
Reported-by: M Hickford
cc @hickford 
Fixes #273
> registry: don't call xmlCleanupParser()

- test/tool-option-parsing.py
We already do so for the non-successful cases, let's do this here too so we know
whether it was a signal or a normal exit.
This should help debugging errors such as [#266 ](https://github.com/xkbcommon/libxkbcommon/pull/266#discussion_r781636339)
cc @hickford
> test: show the tool exit status on failure

- src/registry.c
- test/registry.c
If the XML file is somehow off, don't load entries that are against the spec.
Note that the new tests will fail once #266 works since they don't handle merging yet.
> registry: skip over invalid ISO639 or ISO3166 entries

- src/registry.c
- test/registry.c
Fixes https://github.com/xkbcommon/libxkbcommon/issues/264
> Variants should inherit iso639, iso3166 and brief from parent layout

- test/registry.c
See efa99624320f54e6e1ff24e4c4b1fcecdfba43d5
cc @hickford
> test: add test for variant inheritance of ISO 639/3166 codes

- src/compose/parser.c
- test/compose.c
lokid and hikid actually stores the sibling to current node, which
should not be cleared when override. This would break the sequence with
a common prefix when override another.
Fix #286
Signed-off-by: Weng Xuetian <wengxt@gmail.com>
> Do not clear sibling entries when override.

- src/keysym-utf.c
- test/keysym.c
Not sure what it's doing here, but converting "€" to a keysym
doesn't work with this entry. 0x13a4 doesn't appear in
xkbcommon-keysyms.h. 0x20ac is the keysym documented in the
header (and it's the last entry in the table).
It's been in the table since it was introduced
in e0524296d2e0 ("Add API for getting unicode representation of a
keysym").
> Remove bogus euro sign entry from keysymtab

- tools/interactive-wayland.c
We need to request the lower version of the interface versions we
support and the server supports, not the higher version.
Using the higher version caused crashes due to unbound callbacks on
GNOME, which supports a higher version of `xdg_wm_base`.
> interactive-wayland: Fix interface versioning

- .github/workflows/linux.yml
Let's keep the test logs so we can figure *why* a test failed. And since valgrind tends to spam the logs, let's run a normal test run first to catch any actual test case failures that aren't valgrind-related.
> ci: store the logs on failure and split test and valgrind-test

- .github/workflows/github-release.yml
- .github/workflows/linux.yml
- .github/workflows/macos.yml
- .github/workflows/windows.yml
Node 12 is deprecated so let's bump the actions to newer versions that use Node 16. See
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
> CI: bump a few actions to newer versions

- include/xkbcommon/xkbcommon.h
- include/xkbcommon/xkbregistry.h
- src/compose/parser.c
- src/compose/paths.c
- src/compose/paths.h
- src/compose/table.c
- src/context-priv.c
- src/context.c
- src/context.h
- src/registry.c
- src/utils.h
- src/xkbcomp/rules.c
This flag is useful for clients that may have relatively benign capabilities set, like CAP_SYS_NICE, that also want to use the xkb configuration from the environment and user configs in XDG_CONFIG_HOME.
Fixes #308
> context: add XKB_CONTEXT_NO_SECURE_GETENV flag

- meson.build
This allows xkbcommon to be used as a subproject.
> build: override dependency for use as subproject

- src/keysym.c
Same numeric value for both and the Serbian one has been listed as deprecated for decades.
See https://gitlab.freedesktop.org/xorg/proto/xorgproto/-/merge_requests/69#note_1843415
> keysym: replace deprecated Serbian_DZE with Cyrillic_DZHE

- bench/bench.c
- src/utils.h
- test/common.c
- test/test.h
- tools/tools-common.c
- tools/tools-common.h
`_MSC_VER` is specific to MSVC, but there can be other compilers targeting windows. Hopefully they do define `_WIN32`, so let's use that.
Refs: https://github.com/xkbcommon/libxkbcommon/issues/305
> Possible fix for non-MSVC windows compilers

- meson.build
meson needs to know that the executable tools link against libxkbcommon.dylib so that the
@rpath references used during the build/test phases can be rewritten to full path names on install
Fixes: #327
> meson.build: register libxkbcommon.dylib link

- README.md
- fuzz/fuzz.sh
This is backend-agnostic and the recommended way to invoke compilation.
This requires meson 0.55 (July 2020) and we only require 0.51 but at this point I'm expecting most users who require the README instructions will have a recent-enough meson anyway.
> README: use meson compile/test over ninja

- src/keymap.c
- test/buffercomp.c
As the documentation for `xkb_keymap_new_from_string()` states, the "input string does not have to be zero-terminated". The actual implementation however failed with "unrecognized token/syntax error" when it encountered a null byte.
Fix this by allowing a null byte at the last position of the buffer. Anything else is likely a client error anyway.
Fixes #307
cc @ofourdan
> scanner: allow for a zero terminated string as keymap

- src/context-priv.c
There is no feedback that they are both replaced with default values.
Fixes #336
> Add warning when RMLVO with no layout but variant set

- src/keysym-utf.c
- src/utf8.c
- test/keysym.c
- test/utf8.c
Surrogates are invalid in both [UTF-32](https://www.unicode.org/versions/Unicode15.0.0/ch03.pdf#G28875) and [UTF-8](https://www.unicode.org/versions/Unicode15.0.0/ch03.pdf#G31703).
Fixes #60
> Do not interpret nor emit invalid Unicode encoding forms

- src/compose/parser.c
- src/compose/state.c
- src/compose/table.h
In commit 1638409b22aef33d487863876ab214b949db4984, the number of compose nodes was limited to 65535 to enable "future optimizations", which apparently means slightly reduced memory usage due to fitting in a uint16_t. At this time, it was mentioned that the author was not aware of "any compose files which come close".
However, I'm one of the users that actually do require a larger number of nodes for their compose file. Thus, drop the limit and use a uint32_t again.
> compose: drop the 65535 node limit

- tools/interactive-evdev.c
- tools/xkbcli-interactive-evdev.1
Currently there is no interactive tool allowing to set the include paths of the context, such as in "compile-keymap". Note that only `interactive-evdev` makes sense, because it does not rely on a compositor.
Add `--include` and `--include-defaults` to `interactive-evdev` tool. The code is adapted from `compile-keymap`.
> interactive-evdev: includes options

- test/compose.c
The test `test_from_locale` fails when there is a user-defined compose file, e.g. ~/.XCompose.
Indeed, the function `xkb_compose_table_new_from_locale` use various environment variables to determine the location of the compose file.
Ensure these environment variables are initially explicitly unset, in order to have robust tests.
Fixes #349
> Test (compose): fix assumption on environment variables

- meson.build
- meson_options.txt
The script `ensure-stable-doc-urls.py` relies on the Doxygen output files names. These may change between Doxygen versions, although the Doxygen developers intend stability.
Since the script is useful mainly for the online documentation of xkbcommon, make the target `doc-cool-uris` optional.
See #347
> Add a meson flag to make cool URIs optional

- tools/compile-keymap.c
All of the arguments have defaults, but still an argument is required. Make it work.
> xkbcli: allow compile-keymap without args

- .github/workflows/linux.yml
- .github/workflows/pages.yml
Upload the doxygen output as artifact from the linux build and use that from the pages job where we combine the static website with our newly build HTML docs. The GitHub actions/download-artefact doesn't work across workflows so we use the other popular one that can do this. The rest of the job is basically copy/paste from the "Static HTML" example GitHub provides.
To make this useful as drop-in replacement, replace the one fixed link to the API docs a relative one.
Refs #326
---
- Result rendered into my checkout: https://whot.github.io/libxkbcommon/
- In the [libxkbcommon project settings](https://github.com/xkbcommon/libxkbcommon/settings/pages), `Build and deployment` select the `Github Actions` option (not `Deploy from branch`).
> Configure github pages

- test/state.c
- tools/interactive-wayland.c
Add a constant `EVDEV_OFFSET` to make the semantic of the offset clearer.
Separate PR, as requested in #353
> Replace keycode numeric offset with EVDEV_OFFSET

- include/xkbcommon/xkbcommon.h
- src/keysym.c
- src/keysym.h
- src/utils.h
- src/x11/keymap.c
- src/xkbcomp/expr.c
- src/xkbcomp/parser.y
- test/data/symbols/numeric_keysyms
- test/keymap.c
- test/keysym.c
While working on #332, I realized that numeric keysyms parsing has some issues. Let’s deal with it in this separate PR.
This PR fixes some edges cases and improve tests.
> Fix numeric keysym parsing

- src/xkbcomp/parser.y
Hi,
Thank you for libxkbcommon.
I get this when building -
../src/xkbcomp/parser.y:88.1-12: warning: deprecated directive: ‘%pure-parser’, use ‘%define api.pure’ [-Wdeprecated]
and changed parser.y to use newer method.
Not sure if changing causes more harm than good or if we can version this somehow.
I am using bison 3.5.1
thx
> parser.y update for deprecated %pure-parser

- doc/Doxyfile.in
- doc/introduction-to-xkb.md
- doc/rules-format.md
```
libxkbcommon/doc/introduction-to-xkb.md:67: warning: unable to resolve reference to 'rule-file-format' for \ref command
libxkbcommon/doc/introduction-to-xkb.md:181: warning: unable to resolve reference to 'keymap-text-format-v1' for \ref command
libxkbcommon/doc/rules-format.md:10: warning: unable to resolve reference to 'xkb-intro' for \ref command
```
> doc: fix some Doxygen warnings

- .github/workflows/linux.yml
- meson.build
- test/x11.c
- test/x11comp.c
- test/xvfb-wrapper.c
- test/xvfb-wrapper.h
The X11 test is currently silently skipped in CI. Use a `xvfb` wrapper to ensure to run it. See #339 for the rationale.
The code is adapted from #339 ~and it is intended to be rebased on it, then refactor the x11comp test as well with the wrapper~, which is closed in favour of this new PR.
Question: should we use an option to disable the wrapper, in order to test with a local X11 server as previously?
> Test: Use a xvfb wrapper  for x11 test

- meson.build
- tools/interactive-evdev.c
- tools/interactive-wayland.c
- tools/interactive-x11.c
- tools/tools-common.c
- tools/tools-common.h
I would like to revive #36 but I realize that I use a bunch of `printf` for debugging modifiers.
This MR add new options to `interactive-evdev` for debugging (see commits). Some options use the private API, so I added a non-installable version of the tool with this API.
I did not modify the other tools ATM, because `interactive-evdev` seem the most flexible one, being able to load whatever configuration without depending nor impacting the environment.
There is one commit that improve the display of control characters from key strokes translation.
> Improve interactive tools

- bench/compose-traversal.c
- include/xkbcommon/xkbcommon-compose.h
- meson.build
- src/compose/parser.c
- src/compose/parser.h
- src/compose/table.c
- src/compose/table.h
- src/darray.h
- test/compose.c
- tools/compose.c
- xkbcommon.map
This is a revival of the [`compose-traverse` branch](https://github.com/bluetech/libxkbcommon/tree/compose-traverse) from @bluetech.
Fixes #366
Could be also useful for #361.
> Add iterator API for Compose table

- meson.build
- meson_options.txt
- tools/compile-keymap.c
- tools/interactive-evdev.c
- tools/registry-list.c
- tools/xkbcli-bash-completion.sh
- tools/xkbcli-how-to-type.1
- tools/xkbcli-interactive-evdev.1
- tools/xkbcli.c
WIP. This is the first time I write bash completion, be kind!
> Add bash completions

- src/compose/parser.c
- src/xkbcomp/rules.c
- src/xkbcomp/scanner.c
- test/buffercomp.c
- test/compose.c
- test/data/rules/utf-8_with_bom
- test/rules-file.c
> Skip heading UTF-8 encoded BOM

- src/compose/parser.c
The leading UTF-8 BOM detection code is misplaced as it is executed after each EOL.
Fixed by moving the code before the goto labels.
Sorry for the distraction.
> Compose: Fix UTF-8 BOM detection

- src/state.c
GCC 14 introduces a new -Walloc-size included in -Wextra which gives:
```
src/state.c:589:9: warning: allocation of insufficient size ‘1’ for type ‘struct xkb_state’ with size ‘128’ [-Walloc-size]
```
The calloc prototype is:
```
void *calloc(size_t nmemb, size_t size);
```
So, just swap the number of members and size arguments to match the prototype, as we're initialising 1 struct of size `sizeof(struct xkb_state)`. GCC then sees we're not doing anything wrong.
> state: fix -Walloc-size

- tools/interactive-evdev.c
- tools/interactive-wayland.c
- tools/interactive-x11.c
- tools/tools-common.c
- tools/tools-common.h
- tools/xkbcli-interactive-wayland.1
- tools/xkbcli-interactive-x11.1
Currently only `interactive-evdev` has support for compose. Let’s add X11 and Wayland.
> Compose: add support to all interactive tools

- doc/message-registry.md
- doc/message-registry.yaml
- src/messages-codes.h
- src/xkbcomp/compat.c
- src/xkbcomp/include.c
- src/xkbcomp/include.h
- src/xkbcomp/keycodes.c
- src/xkbcomp/symbols.c
- src/xkbcomp/types.c
- test/buffercomp.c
- test/data/compat/recursive
- test/data/keycodes/recursive
- test/data/symbols/recursive
- test/data/types/recursive
- tools/messages.c
Prevent recursive includes of keymap components by limiting the include depth. This is an alternative design of #389.
This PR has a commit that fixes a memory leak, but should be rebased once #391 is merged.
> Prevent recursive includes of keymap components (using include depth)

- doc/introduction-to-xkb.md
- doc/rules-format.md
- doc/user-configuration.md
In particular, the rules file page was completely broken due to Doxygen limitations.
> Doc: fix malformed links and some typos

- meson.build
- src/compose/dump.h
- src/compose/parser.c
- src/compose/parser.h
- test/compose.c
- test/test.h
- test/tool-option-parsing.py
- tools/compile-compose.c
- tools/xkbcli-bash-completion.sh
- tools/xkbcli-compile-compose.1
- tools/xkbcli.1
- tools/xkbcli.c
> Promote tools/compose to xkbcli-compile-compose

- src/registry.c
- test/registry.c
Previously the attribute “popularity” was completely ignored. It also did not respect the modified DTD, because its default value depends if we are loading an “extras” rules file.
Fixed:
- Always parse the popularity attribute.
- Change the DTD to reflect that the default value is implied.
Fixes #278
> registry: Parse “popularity” attribute

- test/xvfb-wrapper.h
Hi,
when trying to build libxkbcommon with clang+lld on Gentoo and with the `--gc-sections` linker optimization switch, the following errors are produced:
```
[134/150] clang  -o test-x11 test-x11.p/test_x11.c.o -Wl,--as-needed -Wl,--no-undefined -O2 -march=native -pipe -flto -Werror=odr -Werror=strict-aliasing -ffunction-sections -fdata-sections -Wl,-O2 -Wl,--gc-sections -Wl,--icf=all -Wl,--as-needed -fuse-ld=lld -Wl,--start-group libxkbcommon-x11-internal.a libxkbcommon-test-internal.a /usr/lib64/libxcb.so /usr/lib64/libxcb-xkb.so -Wl,--end-group
FAILED: test-x11 
clang  -o test-x11 test-x11.p/test_x11.c.o -Wl,--as-needed -Wl,--no-undefined -O2 -march=native -pipe -flto -Werror=odr -Werror=strict-aliasing -ffunction-sections -fdata-sections -Wl,-O2 -Wl,--gc-sections -Wl,--icf=all …
```
> Fix compilation error with clang when using the "-Wl,--gc-sections" linker optimization

- meson.build
- src/registry.c
- src/util-mem.h
- src/xkbcomp/compat.c
- src/xkbcomp/keycodes.c
- src/xkbcomp/symbols.c
- src/xkbcomp/types.c
Follow-up of [Peter’s suggestion](https://github.com/xkbcommon/libxkbcommon/pull/406#discussion_r1398695593).
> Utils: steal `steal` from libei

- src/state.c
While some transformations are defined in the section “Interpreting the Control Modifier” of the XKB protocol, a lot are not. Documentation is scarce about the topic, so write down some context using the following sources:
- https://en.wikipedia.org/wiki/Caret_notation#Use_in_software
- https://www.vt100.net/shuford/terminal/dec_keyboards_news.txt
- https://misc.openbsd.narkive.com/NvSWf6ax/which-key-shortcuts-are-safe-to-bind-and-some-q-s-about-history-and-os-diffs-re-ctrl-4-means
- https://vt100.net/docs/vt220-rm/chapter3.html#T3-5
@whot @bluetech doc is really scarce, I hope you can give us some light!
Fixes #368
> Add documentation to XkbToControl

- src/utils.h
`ssize_t` is not part of standard C but is specific to POSIX.
> Provide ssize_t for Windows

- doc/keymap-format-text-v1.md
- test/data/symbols/awesome
- test/keymap.c
I couldn't find any reference to *how* the keymap format actually needs to look like if you want multiple keysyms per level. So let's add a test for it and a minimal documentation entry.
> test: add a test for multiple keysyms (and some minimal docs)

- meson.build
- scripts/update-headers.py
- scripts/update-keysyms
- src/keysym-utf.c
- src/keysym.c
- src/keysym.h
- src/keysym.h.jinja
- src/text.c
- test/common.c
- test/compose.c
- test/keysym.c
- tools/compile-compose.c
- tools/how-to-type.c
- tools/tools-common.c
Working on a fix of #413, I realize that some bounds related should be made explicit. 
I added `XKB_KEYSYM_NAME_MAX_SIZE` to the public API and a keysym iterator API for internal use.
> Keysyms: explicit bounds

- src/keysym.c
- test/keysym.c
Fixes #413 and add corresponding tests. Also add some tests for keypad keysyms.
This is based on #414; we should wait for it to be merged.
> Keysyms: fix xkb_keysym_is_modifier

- .github/workflows/linux.yml
- meson.build
- src/keysym.c
- test/keysym.c
There are a few mistakes in the function `XConvertCase`.
Fixed the upper case mappings for:
- `XKB_KEY_ydiaeresis`
- `XKB_KEY_mu`
- `XKB_KEY_ssharp`
Also added ICU optional test.
Notes:
- `xkb_keysym_is_upper` is interpreted as matching the disjunction of the Unicode character properties “Uppercase” or “Titlecase”.
- In Unicode, the upper case of “ß” (`U+00DF`) is *not* “ẞ” (`U+1E9E`) but “SS”. “ẞ” is reserved for text in capitals.
This MR depends on #414 and should be rebased on it.
> Keysyms: Fix case mapping

- scripts/update-keysyms
The file name misses an extension.
> scripts: Fix update-headers command

- src/compose/parser.c
- src/compose/parser.h
- src/compose/state.c
- test/compose.c
- tools/tools-common.c
In the spirit than #414, add explicit bound for compose result string.
This is based on #414; we should wait for it to be merged.
> Compose: explicit result string size

- src/compose/table.c
- test/compose.c
The current `xkb_compose_table_iterator_next` segfaults when used with an empty table. Indeed, in this case we initialize cursors in `xkb_compose_table_iterator_new` with the dummy node and the direction `NODE_LEFT`, but the dummy node is a leaf!
Fixed by initializing with no cursors when the table is has no non-dummy nodes.
> compose: Fix iterator for empty tables

- src/xkbcomp/parser.y
- test/data/keymaps/empty-symbol-decl.xkb
- test/filecomp.c
An empty element is allowed in SymbolsBody definition, so the following keymap is gramatically correct.
```
xkb_keymap {
xkb_symbols "sym" {
key <SPC> {, [Space] };
};
};
```
However, the current parser crashes with the keymap due to null pointer access.
This change fixes the crash.
> Fix crash when an element of SymbolsBody is empty

- tools/interactive-evdev.c
```
Usage: /usr/libexec/xkbcommon/xkbcli-interactive-evdev [--include=<path>] [--include-defaults] [--rules=<rules>] [--model=<model>] [--layout=<layout>] [--variant=<variant>] [--options=<options>]
or: /usr/libexec/xkbcommon/xkbcli-interactive-evdev --keymap <path to keymap file>
```
after:
```
Usage: ./build/xkbcli-interactive-evdev [--include=<path>] [--include-defaults] [--rules=<rules>] [--model=<model>] [--layout=<layout>] [--variant=<variant>] [--options=<options>]
or: ./build/xkbcli-interactive-evdev --keymap <path to keymap file>
```
> interactive-evdev: align Usage and or in the help output

- doc/Doxyfile.in
warning: Tag 'HTML_TIMESTAMP' at line 44 of file '/home/whot/xorg/lib/libxkbcommon/build/Doxyfile' has become obsolete.
> doc: remove obsolete HTML_TIMESTAMP

- tools/tools-common.c
In commit 8cca3a7bfb185876994d6ec3d25cda88e5640a4d the buffer for the keysym was extended to accommodate for up to XKB_COMPOSE_MAX_STRING_SIZE bytes. This caused the printf to expand to the same width for the keysym alone, making the output less useful. Drop this back down to the same width it was before.
cc @wismill
> interactive-evdev: reduce the space allocated for keysyms

- src/xkbcomp/rules.c
- test/data/rules/inc-no-newline
- test/rules-file-includes.c
Rules file parser allows constructs like
```
!include "foo" !include "bar" !layout = symbols
```
This is most likely an oversight in original code.
Closes #452
> xkbcomp: Require newline after !include line in rules files

- meson.build
- test/common.c
- test/keyseq.c
- tools/tools-common.c
- tools/tools-common.h
`test_key_seq` takes a list of key operations and if one fails it can be a bit tricky to figure out why (e.g. in my case I knew it was RALT but didn't realise it was the up, not the down that triggered the error).
Let's help with this by printing the operation and the keymap state just like e.g. `interactive-evdev` does.
> Some improvements to test debugging

- tools/tools-common.c
We avoid this header due to its locale dependence. This include seems like a leftover in 44029221e8423f1ca93470952542a0517a208d42.
> tools: remove unused `#incldue <ctype.h>`

- .github/workflows/linux.yml
- meson_options.txt
The only docs we build is the doxygen API and I reckon there's a near-zero amount of users who actually want these built locally instead of just browsing the online doc.
Let's not build this by default, dropping the requirement on doxygen and speeding up the build by quite a fair bit.
--
Replaces #471 because for some reason github doesn't notice my force-pushes on that.
> meson: disable doc builds by default

- .github/workflows/github-release.yml
- .github/workflows/linux.yml
- .github/workflows/macos.yml
- .github/workflows/pages.yml
- .github/workflows/windows.yml
- use py3.12 for ci
- bump action dependencies
---
- https://github.com/Homebrew/homebrew-core/pull/165881
cc @wismill
> improve CI setup

- src/xkbcomp/rules.c
This pull request modifies a line of code in `xkbcomp/rules.c` , in which the `mapping.layout_idx` was used to index the `rmlvo.variants`. 
Is it correct that instead, `mapping.variant_idx` should be used here?
Thanks
> Small fix: in RMLVO, use `variant_idx` to index variants instead of `layout_idx`

- NEWS.md
I think we are ready for a new release. There are a few MRs ( #391, #415, #434, #440) that would make a release worth on their own.
Updated NEWS.
TODO:
Few questions:
- Is the changelog too detailed?
- Should the keysyms update goes to “breaking changes”? I consider it more as a fix, but it does break anything that rely on the reverted canonical names.
> Prepare for 1.7.0

- meson.build
- test/xvfb-wrapper.c
> Test: add warning for missing Xvfb

- tools/xkbcli-compile-compose.1
- tools/xkbcli-compile-keymap.1
- tools/xkbcli-how-to-type.1
- tools/xkbcli-interactive-evdev.1
- tools/xkbcli-interactive-wayland.1
- tools/xkbcli-interactive-x11.1
- tools/xkbcli-list.1
- tools/xkbcli.1
Previously on FreeBSD/mandoc (probably affecting others), everything except xkbcli was being listed twice and wrapping in apropos because mdoc(7) names should not have spaces or be different than the title.
Further, xkb is already parsed in search results by being in the name, so expand xkb to "X keyboard" so that they match for apropos keyboard. We did this already in xkbutils, which matches setxkbmap.
These don't need to be quoted literals, and - doesn't need to be escaped, but I left them because there may be environments which are not to spec, but I'm happy to ammend this commit if that cleanup seems desirable (works on Linux/groff).
> doc (manuals): clean and expand apropos results

- .github/workflows/linux.yml
- .pre-commit-config.yaml
- scripts/perfect_hash.py
- test/symbols-leak-test.py
- Drop `black` for pre-commit and use `ruff-format` instead (see [xkeyboard-config](https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/merge_requests/647) move)
- Use `ruff format` in CI
Fixes #376
> CI: Add ruff formatting

- changes/build/+meson_bump.breaking.md
- changes/build/481.bugfix.md
- meson.build
Gate the use of `--undefined-version` in the linker because it breaks on older GNU `ld`: https://gnats.netbsd.org/cgi-bin/query-pr-single.pl?number=58272.
Fixes #481
@glechapelain @eli-schwartz
> build: Check for --undefined-version support

- changes/api/418.bugfix.md
- include/xkbcommon/xkbcommon.h
- src/compose/state.c
- src/keysym-utf.c
- src/keysym.h
- src/keysym.h.jinja
- src/state.c
- test/keysym.c
- test/utf8.c
- tools/tools-common.c
Require only 5 bytes for the buffer of `xkb_keysym_to_utf8`, as UTF-8 encodes code points on up to 4 bytes + 1 byte for the NULL-terminating byte.
Previous standard [RFC 2279] (1998) required up to 6 bytes per code point, but has been superseded by [RFC 3629] (2003).
Note that the commit e0524296 that introduced this API is from 2012, which is 9 years after the new standard was introduced.
This PR modifies quite a lot of files (but with tiny diff), because we now enforce to use minimal buffer size internally.
Tests were already added in #414.
[RFC 2279]: https://datatracker.ietf.org/doc/html/rfc2279
[RFC 3629]: https://datatracker.ietf.org/doc/html/rfc3629
Fixes #418
> keysyms: Require only 5 bytes for UTF-8 encoding

- src/compose/dump.h
- src/compose/table.c
- test/compose.c
- test/keysym.c
- test/registry.c
- test/xvfb-wrapper.c
- tools/interactive-wayland.c
- tools/interactive-x11.c
This fixes a bunch of minor covscan/scan-build complaints, mostly in the test code.
I think there's only one legitimate bug in `test/registry.c` where we need `sizeof()` -> `ARRAY_SIZE()`. The rest is mostly to shut up the analyziers.
There are still a few left over but they're deep in the parsing code and I couldn't immediately tell if they were actual bugs (I think they are false positives).
> Scan-build and covscan fixes

- meson.build
Rational (from: https://gitlab.freedesktop.org/wayland/wayland/-/issues/175):
The ABI of a shared library on Linux is given by a major version, which is part of the SONAME and is incremented (rarely) on incompatible changes, and a minor version, which is part of the basename of the regular file to which the SONAME provides a symlink. It's conventional to manage the ABI version in the style of semantic versioning (major.minor.micro where the major version goes up for incompatible changes, the minor version goes up for new ABI, or the micro version goes up for internal fixes), although this is not strictly required.
The minor version is used by `ldconfig(8)` and by some projects to choose which of potentially several copies of a library is the newest; keeping it the same means we can't …
> build: Set the ABI version properly

- bench/compose-traversal.c
- meson.build
- src/compose/dump.c
- src/compose/dump.h
- src/compose/escape.h
- src/compose/table.c
- src/compose/table.h
- test/compose-iter.c
- test/compose-iter.h
- test/compose.c
- test/shuffle-lines.c
- test/shuffle-lines.h
- tools/compile-compose.c
This is a follow-up of #367 (see the [motivation](https://github.com/xkbcommon/libxkbcommon/pull/367#issuecomment-1732521452)). The aim is to explore better implementations of the compose traversal API, in particular `xkb_compose_table_iterator_next`.
~Currently it is in the state of #367 before removing alternative implementation and squashing. It will need to be rebased once #367 is merged.~ Done
I kept the 2 implementations (see the [benchmarks](https://github.com/xkbcommon/libxkbcommon/pull/367#issuecomment-1722517850)) in an intermediate commit for testing.
TODO:
> Improve compose traverse perf

- changes/api/+compose-and-kana-led-names.features.md
- include/xkbcommon/xkbcommon-names.h
The end goal is to be able to press `Num Lock`, `Caps Lock`, `Scroll Lock`, `Compose` or `Kana` and have either of the 5 LEDs on my QMK keyboard light up.
I could use a bit of help here.
This is a continuation of https://gitlab.freedesktop.org/libinput/libinput/-/merge_requests/990 and is directly related to the [current WIP for kwin](https://invent.kde.org/plasma/kwin/-/merge_requests/5627) for adding the same two LED keys.
[HID spec](https://usb.org/sites/default/files/hid1_11.pdf) defines five LEDs, but only the first 3 are currently supported by XKB and most of the Linux tooling:
I am not familiar with XKB, where else do I need to put the necessary definitions?
> Add XKB_LED_NAME_COMPOSE and XKB_LED_NAME_KANA

- changes/api/497.bugfix.md
- doc/rules-format.md
- src/xkbcomp/rules.c
- test/data/rules/groups
- test/data/rules/wildcard
- test/rules-file.c
The handling of wild card `*` is different in libxkbfile and X server: wild card matches empty strings for model and option but not for layout nor variant, while in libxkbcommon wild cards always match empty strings.
See:
- https://gitlab.freedesktop.org/xorg/lib/libxkbfile/-/blob/bf985c68acb1244f51ec91414532a2347fbc1c4c/src/maprules.c#L687
- https://gitlab.freedesktop.org/xorg/lib/libxkbfile/-/blob/bf985c68acb1244f51ec91414532a2347fbc1c4c/src/maprules.c#L712
The difference of handling between the components is unfortunately not documented, but we should follow the behavior of the original implementations for consistency.
- Fixed by implementing the same behavior than libxkbfile.
- Added tests and fixed failing tests.
Fixes #497
> rules: Fix wild card handling

- changes/tools/+how-to-type-format.feature.md
- meson.build
- src/utf8-decoding.c
- src/utf8-decoding.h
- test/utf8.c
- tools/how-to-type.c
- tools/xkbcli-how-to-type.1
Currently the positional parameter of the CLI is either a Unicode code
point or a keysym. However their respective format is not documented.
It turns out that there are multiple issues due to the use of `strtol`:
- Code points can be parsed as octal, decimal and hexadecimal while
keysyms can only be parsed as hexadecimal. Some programs outputs
keysyms in their decimal form (e.g. `wev`) so it is worth to bring
symmetry with code points.
- Octal format is unusual for both and is triggered by leading zeros,
which is unintuitive in this context.
- `U+NNNN` format is the standard format for Unicode code points but is
not supported.
- Plain characters are not supported, e.g.: a, é, ß, Æ, γ, 🦆, etc.
Although this is probably the easiest format for most users.
Fixed the issues above:
- Allow the …
> xkbcli how-to-type: Enhance arguments parsing & doc

- .github/workflows/macos.yml
- Bump macOS image, as macOS 12 has been deprecated. See: https://github.com/actions/runner-images?tab=readme-ov-file#available-images
- Install PyYaml via Pip, as it has been disabled in Brew. See: https://docs.brew.sh/Homebrew-and-Python#pep-668-python312-and-virtual-environments
- Fix libxml2 not linked.
> ci: Fix macOS

- src/xkbcomp/parser.y
- test/buffercomp.c
Currently we are too liberal when parsing symbols lists: e.g. `[{a,{b}}]` is parsed as `[{a,b}]` but it should be rejected.
> symbols: Fix too liberal parsing of keysyms lists

- changes/api/511.explicit-interp-per-group.bugfix.md
- meson.build
- src/keymap.h
- src/x11/keymap.c
- src/xkbcomp/keymap-dump.c
- src/xkbcomp/keymap.c
- src/xkbcomp/symbols.c
- test/compose.c
- test/data/keymaps/explicit-actions.xkb
- test/keyseq.c
- test/stringcomp.c
- test/utils-text.c
- test/utils-text.h
- test/utils.c
Previously setting explicit actions for a group in symbols files made the parser skip compatibility interpretations for the corresponding *whole* key, so the other groups with *no* explicit actions could result broken on some levels.
In the following example, `<RALT>` would have an action on group 2, because it is explicit, but none on group 1 because interpretation are also skipped there as a side effect:
```c
key <RALT> {
symbols[1]= [              ISO_Level3_Shift ],
symbols[2]= [              ISO_Level3_Shift ],
actions[2]= [ SetMods(modifiers=LevelThree) ]
};
```
Fixed by skipping interpretations *only* for groups with explicit actions.
We still set `key->explicit |= EXPLICIT_INTERP` if at least one group has explicit actions. In such case, when dumping a keymap, we will write …
> symbols: Skip interprets only for groups with explicit actions

- bench/rules.c
- changes/api/262.only-one-group-per-key.bugfix.md
- src/keymap.h
- src/xkbcomp/rules.c
- src/xkbcomp/rules.h
- src/xkbcomp/symbols.c
- src/xkbcomp/xkbcomp.c
- test/data/rules/multiple-groups
- test/data/symbols/multiple-groups
- test/keymap.c
- test/rules-file-includes.c
- test/rules-file.c
- tools/compile-keymap.c
Currently `xkb_keymap_num_layouts` may return a greater number than the number of layouts configured using RMLVO, because we allow symbols sections to define various groups per key.
This is unintuitive and kind of buggy: groups should be added via rules by setting an explicit `:n` modifier.
Fix: when parsing a keymap using RMLVO resolution:
- Get the expected layouts count from the resulting KcCGST.
- Drop the groups after the first one in included symbols sections. This will ensure that a symbol section can only define one group per key.
Notes:
- Compiling a keymap string directly is unaffected.
- RMLVO resolution may still produce more groups than the input layouts. Indeed, some legacy rules in xkeyboard-config rely on this to insert automatically a US layout before to the given …
> Allow only the first group in symbols sections when using RMLVO

- changes/tools/+dump-keymap.feature.md
- meson.build
- tools/interactive-wayland.c
- tools/interactive-x11.c
- tools/xkbcli-dump-keymap-wayland.1
- tools/xkbcli-dump-keymap-x11.1
- tools/xkbcli-interactive-wayland.1
- tools/xkbcli.c
There is currently no easy way to dump a keymap from a Wayland compositor, such as `xkbcomp -xkb $DISPLAY -` could do for X servers.
As `xkbcomp` may not be intuitive, a corresponding tool for X servers would also be useful.
Add the tools `xkbcli-dump-keymap-{wayland,x11}` by tweaking the existing `xkbcli-interactive-{wayland,x11}` tools.
Commands names subject to bikeshedding.
> tools: Add xkbcli dump-keymap-{wayland,x11}

- changes/api/529.fix-xml-error-handler.bugfix.md
- meson.build
- src/registry.c
- test/registry.c
Leaving the custom error handler could have resulted in a crash after the context has been freed.
Closes: https://github.com/xkbcommon/libxkbcommon/issues/529
> registry: Restore default libxml2 error handler after parsing

- meson.build
- src/registry.c
See: #529 and the related comment in the [original Gnome issue](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/7974#note_2245926).
> Registry: use safe libxml2 API

- test/xkeyboard-config-test.py.in
- Refactor to more modern Python
- Allow iterating over models too
- Add filter for models and options
- Add “short output” option
> tests: Improve xkeyboard-config script

- changes/tools/+test-flag.feature.md
- test/xkeyboard-config-test.py.in
- tools/compile-compose.c
- tools/compile-keymap.c
- tools/xkbcli-compile-compose.1
- tools/xkbcli-compile-keymap.1
- Added `--test` option to `xkbcli compile-{keymap,compose}` tool, to enable testing compilation without printing the resulting file.
- Improved `xkeyboard-config-test` script:
- Make use of previous new option to speedup test (≈25% faster).
- Refactored to make keymap writing in workers, not in the main process.
- Added `--compress` option to enable keymap compression with gunzip.
> Tools: added --test option

- src/compose/paths.c
Patch authored by Jeffrey Cliff, send by email:
i don't have access to github but this patch enabled me to compile libxkbcommon with -std=gnu23
otherwise the following compilation error will result :
../src/compose/paths.c:70:16: error: incompatible types when returning type ‘_Bool’ but ‘char *’ was expected
( gcc (GCC) 15.0.0 20240509 (experimental) )
> compose/paths: fix `false` <-> `NULL` confusion, errors on C23

- towncrier.toml
Towncrier doc states that the `underlines` setting is not used with Markdown files, so let’s apply the tag ourselves.
> changelog: Fix release title format

- .github/workflows/linux.yml
Doesn't like it when two jobs from the same run upload the same name.
> ci: fix upload artifact conflict

- .github/workflows/pages.yml
We use the xkbcommon/website pages for the website, so here it's just for previewing and we only need to the docs, not the website.
Fix #561.
> ci: upload only doxygen docs to pages

- RELEASING.md
I hope I didn't forget anything. We can certainly automate some of this, but this is documenting what I am currently doing.
Note that I explicitly decided to remove publishing a tarball. Given what happened with [xz backdoor](https://en.wikipedia.org/wiki/XZ_Utils_backdoor), I think we are better off without them. I'm pretty sure most distros build directly from git these days. We should make a prominent note of this change in the announcement email. Old tarballs will not be removed.
Let me know if you have any comments.
> Add "How to make a libxkbcommon release"

- src/xkbcomp/parser.y
The following syntax does not parse in xkbcommon, but it does in xkbcomp:
```
xkb_symbols "x" {
key <AD01> { };
};
```
While the usefulness of such statement is debatable, the fact that it does parse in xkbcomp and that tools may generate such keymap entry make it relevant to handle.
See: #565
> symbols: Parse empty key

- doc/debugging.md
- doc/user-configuration.md
- meson.build
> doc: Add debugging page and warning about session restart

- changes/api/+fix-x11-action-only-handling.bugfix.md
- src/x11/keymap.c
- test/data/keymaps/host.xkb
When getting the keymap from X11, the following:
```
key <AD01> { actions=[SetGroup(2)] };
```
is currently converted to:
```
key <AD01> { };
```
This commit fixes dropping a defined action when the keysym is undefined
> x11: Keep level when the keysym is undefined but not the action

- src/xkbcomp/compat.c
- test/data/keymaps/merge-modes/compat.xkb
- test/merge_modes.c
> compat: Fix Interp & LED merge modes

- changes/api/583.bugfix.md
- src/state.c
- test/data/symbols/simultaneous-mods-latches
- test/keyseq.c
> Clear mods properly with `|=`

- src/atom.c
- src/compose/parser.c
- src/compose/table.h
- src/keymap-priv.c
- src/state.c
- src/text.c
- src/x11/keymap.c
- src/xkbcomp/expr.c
- src/xkbcomp/keymap-dump.c
- src/xkbcomp/keymap.c
- src/xkbcomp/rules.c
- src/xkbcomp/symbols.c
- test/common.c
- test/keymap.c
- test/keyseq.c
- test/modifiers.c
- test/state.c
- tools/how-to-type.c
- tools/tools-common.c
Fix a few of them and make the rest portable using `UINTn_C` macros.
@whot @bluetech
> Fix integer literal suffixes

- changes/build/481.bugfix.md
- meson.build
- test/meson_test.map
Various problems can occur when using the full `xkbcommon.map` file when checking whether the `--version-script` linker option works in `meson.build`. See https://lists.freebsd.org/archives/freebsd-current/2025-January/006888.html for an example.
For instance, newer linkers typically complain about non-existing symbols, so in commit ebe4157 `--undefined-version` was added to work around that. But then in commit 1d8a25d6 another workaround needed to be added for older linkers.
It is better to use a minimalistic linker script for testing instead. The other workarounds can then be removed.
> Use test map for checking --version-script, instead of full map

- changes/api/+dump-explicit-vmod-mappings.bugfix.md
- src/keymap.h
- src/text.c
- src/xkbcomp/keymap-dump.c
- src/xkbcomp/vmod.c
- test/data/keymaps/stringcomp.data
xkbcommon already allow pure virtual modifiers (see #450) via explicit mapping (see @mahkoh [comment](https://github.com/xkbcommon/libxkbcommon/pull/450#issuecomment-2575248313)). But it does not roundtrip, because we do not dump the virtual modifier mappings.
This PR enable dumping the *explicit* mappings. The following issue may be dealt with in a follow-up MR:
> The assignment of pure virtual modifiers to bits is implicit. If both parties don't agree on the order in which virtual modifiers are assigned, they cannot communicate. With the mapping explicitly spelled out, it is at least possible for a client to detect the desired bit offset.
> Fix explicit vmod dump

- bench/compile-keymap.c
Embedding a directive within macro arguments has undefined behavior.
> bench: Fix embedded directive within macro arguments

- src/xkbcomp/action.c
Currently we accept values of -255..255 while parsing the screen value of `SwitchScreen` actions`, but then we silently cast it against `int8_t`, i.e. in range -128..127.
We actually do as xkbcomp, but this seems a bug because the target storage is a `char`. Let’s simply raise a parse error if the value does not fit in our type.
Fixes #571
CC @wysiwys
> actions: Fix SwitchScreen screen value range

- src/xkbcomp/ast-build.c
- src/xkbcomp/ast-build.h
- src/xkbcomp/ast.h
- src/xkbcomp/expr.c
- src/xkbcomp/parser.y
- src/xkbcomp/symbols.c
- test/buffercomp.c
Detected using `clang-tidy`. We probably need to activate some automatic fuzzer to ensure there are no other hazardous code paths!
> symbols: Fix 2 possible null pointer deferences

- scripts/makekeys
- scripts/update-keysyms
- src/xkbcomp/parser.y
Due to how our parser is implemented, keysyms names that are also valid keywords require special handling.
Added a check for these clashes in the keysym generator. The only current clash, `section`, is already handled. Note that it means that `section`, `Section`, `sEcTiOn` all parse to the same keysym.
Hopefully we will never have a clash again, but the keysyms are not a frozen set.
---
I got puzzled by the following excerpt in `parser.y` and decided to investigate.
```
KeySym          :       IDENT
…
|       SECTION { $$ = XKB_KEY_section; }
```
> keysyms: Check clashes between keysyms names and keywords

- src/state.c
- test/data/symbols/latch
- test/keyseq.c
In essence empty levels are levels with just a `NoSymbol` keysym and a `NoAction()`, which breaks latches.
- Fixed regression introduced in #487.
- Added a bunch of tests that were previously in #611. The ambiguous cases are tested with the current behavior but I left the behavior introduced in #611 commented.
- Added tests also for the case where the keycode is unknown.
Fixes #613
TODO:
CC @mahkoh
> Fix latch not broken by empty level

- test/data/locale/en_US.UTF-8/Compose
Context: [see my comment](https://github.com/xkbcommon/libxkbcommon/pull/623#discussion_r1933226393) in #623.
The data set is big enough so we can just drop most sequences with deprecated keysyms and fix most keysyms an alternative non-deprecated name.
We keep a handful of them for testing purpose.
> tests: Fix deprecated keysyms in Compose data

- test/compose.c
They're a *bit* too slow for interactive test runs when running in debug+sanitizers.
> test/compose: reduce quickcheck iterations

- src/darray.h
- src/keymap.h
- src/xkbcomp/expr.c
- src/xkbcomp/keycodes.c
- test/buffercomp.c
Our current implementation uses continuous arrays indexed by keycodes and levels. This is simple and good enough for realistic keymaps. However, they are allowed to have big values that will lead to either memory exhaustion or a waste of memory (sparse arrays).
Added the much stricter upper bound `0xfff` that should still be plenty enough and provides stronger memory security.
> xkbcomp: Add stricter bounds for keycodes and levels

- src/compose/parser.c
- test/log.c
Let’s check a bit more our logs, especially the token positions.
> test: Add check for keymap and compose compilation logs

- meson.build
- src/compose/parser.c
- src/scanner-utils.c
- src/scanner-utils.h
- src/xkbcomp/rules.c
- src/xkbcomp/scanner.c
The scanner functions are hot, and the line/column location tracking is quite expensive. We only use it for errors, which don't need to be fast, because we bail if there are too many; and for warnings, which are usually not shown by default. So only keep the token start pos, and compute the line/column lazily from that. This will also allow some further improvements ahead.
bench/rulescomp
```
before: compiled 1000 keymaps in 1.669028s
after:  compiled 1000 keymaps in 1.550411s
```
bench/compose:
```
before: compiled 1000 compose tables in 2.145217s
after:  compiled 1000 compose tables in 2.016044s
```
> scanner: compute token line/column lazily on errors

- changes/tools/+compile-compose.feature.md
- meson.build
- tools/compile-compose.c
- tools/compile-keymap.c
- tools/xkbcli-compile-compose.1
> tools: Enable Compose file positional argument and piping

- src/xkbcomp/ast-build.c
- src/xkbcomp/ast-build.h
- src/xkbcomp/ast.h
- src/xkbcomp/parser.y
- src/xkbcomp/symbols.c
The AST is heavily based on intrusive lists for representing lists, but actions and keysyms are an exception, instead using darray. I don't see any reason for this; it ends up allocating more, and we don't especially need a flat array for this.
Change it to use the familiar linked-list style.
bench/rulescomp allocations, before:
```
total heap usage: 11,391,536 allocs, 11,391,536 frees, 511,335,213 bytes allocated
```
after:
```
total heap usage: 10,965,536 allocs, 10,965,536 frees, 496,327,213 bytes allocated
```
> xkbcomp: rework ActionList and KeysymList AST representation

- .github/workflows/github-release.yml
Fixes 737706fe83f2 doc: Use towncrier to handle release notes
> ci: fix link to NEWS file in releases

- scripts/update-keywords
- src/xkbcomp/keywords.c
- src/xkbcomp/keywords.gperf
- src/xkbcomp/scanner.c
The tokens don't have escapes so no need to use the `buf` for them.
> xkbcomp/scanner: avoid extra copies for keynames, keywords, identifiers

- src/xkbcomp/keymap.c
Reuse the darray.
memusage ./release/bench-compile-keymap --iter=1000 --layout us,de --variant ,neo
Before:
Memory usage summary: heap total: 552866360, heap peak: 581022, stack peak: 18848
total calls   total memory   failed calls
realloc|    2035244      211110112              0  (nomove:37629, dec:0, free:0)
After:
Memory usage summary: heap total: 534063576, heap peak: 581022, stack peak: 18848
total calls   total memory   failed calls
realloc|    1447657      192307328              0  (nomove:37629, dec:0, free:0)
> xkbcomp/keymap: avoid some allocations in ApplyInterpsToKey

- src/compose/paths.h
> Replace include guards by `#pragma once` (again)

- src/scanner-utils.h
- src/xkbcomp/parser-priv.h
- src/xkbcomp/parser.y
- src/xkbcomp/rules.c
- src/xkbcomp/scanner.c
The allocation is immediately discarded, either turned into a keysym or
an atom. So use an sval slice into the input string instead strdup'ing.
memusage ./release/bench-compile-keymap --iter=1000 --layout us,de --variant ,neo
Before:
Memory usage summary: heap total: 534063576, heap peak: 581022, stack peak: 18848
total calls   total memory   failed calls
malloc|   11240525      291897104              0
realloc|    1447657      192307328              0  (nomove:37629, dec:0, free:0)
calloc|     430573       49859144              0
free|   13993903      534063576
After:
Memory usage summary: heap total: 506839909, heap peak: 581022, stack peak: 18960
total calls   total memory   failed calls
malloc|    8016419      264673437              0
realloc|    1447657      192307328              0 …
> xkbcomp/scanner: avoid unneeded strdup of IDENT tokens

- src/context.c
- src/keymap-priv.c
- src/keymap.c
- src/keysym.c
- src/state.c
- src/text.h
- src/xkbcomp/action.c
- src/xkbcomp/ast-build.c
- src/xkbcomp/ast-build.h
- src/xkbcomp/ast.h
- src/xkbcomp/compat.c
- src/xkbcomp/expr.c
- src/xkbcomp/expr.h
- src/xkbcomp/keycodes.c
- src/xkbcomp/keymap-dump.c
- src/xkbcomp/scanner.c
- src/xkbcomp/symbols.c
- src/xkbcomp/types.c
- src/xkbcomp/vmod.c
- test/buffercomp.c
- test/common.c
- test/data/keymaps/integers-overflow.xkb
- test/data/keymaps/integers.xkb
- test/data/keymaps/masks.xkb
- test/merge_modes.c
- test/stringcomp.c
- test/utils-text.c
- test/x11comp.c
- tools/tools-common.c
WIP, made public only to make you aware I am working on this.
Follow-up of #604 that is mostly a refactor of the parser for integers. Will probably split the minor refactoring in another PR.
Fixes #594
> Fix numbers types

- tools/compile-keymap.c
Values may be read from the environment!
While working on a xkbcomp MR I was very confused by `<BKSP>` being mapped differently with and without an option that does *not* affect it. It turns out it is just `compile-keymap` that replaces null options with my env variable `$XKB_DEFAULT_OPTIONS = terminate:ctrl_alt_bksp`, as expected.
But debugging with `--kccgst` did not help, because it does not take the environment into account.
Now I am wondering how we could document this better in the tool and if how to read the env to output `usage` with correct default values.
> tools: Fix compile-keymap default KcCGST values

- src/keymap-priv.c
Spotted by `clang-tidy`:
```
../src/keymap-priv.c:146:16: warning: comparing object representation of
type 'union xkb_action' which does not have
a unique object representation; consider
comparing the members of the object manually
[bugprone-suspicious-memory-comparison]
````
Indeed, from “EXP42-C. Do not compare padding data”[^1]:
> unnamed members of objects of structure and union type do not participate
> in initialization. Unnamed members of structure objects have indeterminate
> representation even after initialization.
But since we [zero the action](https://github.com/xkbcommon/libxkbcommon/blob/350931add1552013e3ac77dda6752e1c4cad44e7/src/xkbcomp/symbols.c#L912), I do not think the current behavior can cause a bug, can it?
Fixed by using a dedicated comparison function for `union …
> xkbcomp: Fix incorrect memory comparison

- changes/tools/+enable-environment-names.breaking.md
- test/tool-option-parsing.py
- tools/compile-keymap.c
- tools/how-to-type.c
- tools/interactive-evdev.c
- tools/xkbcli-compile-keymap.1
- tools/xkbcli-how-to-type.1
- tools/xkbcli-interactive-evdev.1
Our tools are debugging tools and as such we need to have complete control to be able to reproduce setups. This is not currently the case, as we do not use `XKB_CONTEXT_NO_ENVIRONMENT_NAMES` by default nor can we set it.
So it is very easy to forget about the various `XKB_DEFAULT_*` environement variables for the default RMLVO values, then to get puzzled by unexpected results.
Added to that, these environment variables do not work correctly in `xkbcli-compile-xeymap`: calling the tool without RMLVO values will use these variables only if the RMLVO values are set explicitly empty or if the various *constants* `DEFAULT_XKB_*` are empty. This is unexpected, as the environment variables should *always* be used unless:
- `XKB_CONTEXT_NO_ENVIRONMENT_NAMES` is used (not the case here);
- the …
> tools: Do not load names from the environment by default

- .clang-tidy
- bench/bench.c
- bench/keysym-case-mappings.c
- scripts/update-keysyms-names-handling.py
- src/ks_tables.h
- src/scanner-utils.h
- src/utf8.c
- src/xkbcomp/keymap.c
- src/xkbcomp/rules.c
- src/xkbcomp/scanner.c
- src/xkbcomp/symbols.c
- test/common.c
- test/keymap.c
- test/merge_modes.h
- test/registry.c
- test/rules-file.c
- test/xvfb-wrapper.c
- tools/interactive-wayland.c
~~CI will pass once #661 is merged.~~
EDIT: removed clang-tidy CI.
> Clang tidy: round 2

- README.md
It’s a *breaking* change of Doxygen. Now it’s called “topics”.
I’m getting tired of fixing Doxygen’s lack of stability.
Fixes #666
> doc: Fix link to modules

- doc/rules-format.md
- doc/user-configuration.md
Options are always applied depending of their order in the relevant rules files, independently of their order in the relevant RMLVO config.
Since this is counter-intuitive (e.g. when using `xkbcli`), let’s highlight this in the documentation.
Fixes #672
> doc: Warn about the options order

- changes/api/+group-wrap.bugfix.md
- src/keymap-priv.c
- test/state.c
Consider num_groups = 1.
Fixes: 67b03cea ("state: correctly wrap state->locked_group and ->group")
-----
This should be backported.
> keymap: fix modular arithmetic

- src/xkbcomp/ast-build.c
The expression AST constructors all return `ExprDef *`. `ExprDef` is a union of all expr types. As a memory optimization, instead of allocating `sizeof(ExprDef)`, we only allocate the size of the actual type (e.g. `sizeof(ExprBinary)`) which is sometimes smaller than `sizeof(ExprDef)`. This is probably undefined behavior, and gcc (with optimization turned on) complains about it, for example:
src/xkbcomp/ast-build.c:69:23: warning: array subscript ‘ExprDef[0]’ is partly outside array bounds of ‘unsigned char[24]’ [-Warray-bounds=]
Since it doesn't save that much memory, drop this optimization.
Fix #292.
> xkbcomp/ast-build: fix possible UB in expr AST node allocations

- .github/workflows/linux.yml
- src/text.c
- src/text.h
- src/xkbcomp/compat.c
- src/xkbcomp/keymap-dump.c
- src/xkbcomp/types.c
- src/xkbcomp/vmod.c
When logging about virtual modifier *explicit* mappings, we should always use only real modifiers or hexadecimal numbers to print the mask.
Consider:
```
virtual_modifiers M1, M2=0x200, M2=0x400;
```
Before this commit we would get the following warning:
```
WARNING: Virtual modifier M2 defined multiple times; Using M2, ignoring M1
```
while we would prefer the less confusing:
```
WARNING: Virtual modifier M2 defined multiple times; Using 0x400, ignoring 0x200
```
> xkbcomp: Improve logging of virtual modifiers

- src/registry.c
- src/xkbcomp/keycodes.c
- test/buffercomp.c
- test/data/keymaps/keycodes-bounds-multiple-1.xkb
- test/data/keymaps/keycodes-bounds-single-1.xkb
- test/data/keymaps/keycodes-bounds-single-2.xkb
- Refactor to check conflicts first for the key names and then for the keycodes. This seems more usefull for the user and enable further memory optimizations.
- Do not allocate until we are sure to add the keycode. The bounds are only updated afterwards, so the call to `FindKeyByName` should be more efficient.
- Fixed keycodes bounds not shrunk correctly when an existing keycode is overridden.
- Do not prepare keyname strings for logging if we are not going to use them.
The bug is really minor. Do not expect much perf improvement in usual cases. 
*However*, this fix is mandatory for testing #592.
> xkbcomp: Fix keycodes bounds

- bench/rules.c
- changes/api/669.feature.md
- changes/tools/669.feature.md
- include/xkbcommon/xkbcommon.h
- meson.build
- src/xkbcomp/ast-build.c
- src/xkbcomp/rules.c
- src/xkbcomp/xkbcomp-priv.h
- src/xkbcomp/xkbcomp.c
- test/rules-file-includes.c
- test/rules-file.c
- test/tool-option-parsing.py
- tools/compile-keymap.c
- tools/xkbcli-compile-keymap.1
- xkbcommon.map
- rules: Added `xkb_components_names_from_rules()`
This is mainly for debugging purposes and to enable displaying KcCGST values from RMLVO resolution in `xkbcli compile-keymap --kccgst`.
- tools: Make `--kccgst` `compile-keymap` option public
The new public option `--kccgst` enables to display the result of RMLVO resolution to KcCGST components.
This option has the same function than `setxkbmap -print`. This is particularly useful for debugging issues with the rules.
Before this commit it was a private API. This commit enables us to remove the *internal* version of `xkbcli-compile-keymap`.
Fixes #669
> Rules: KcCGST public API

- changes/tools/+honor-locale.feature.md
- tools/check-messages.c
- tools/compile-keymap.c
- tools/export-keysyms.c
- tools/how-to-type.c
- tools/interactive-wayland.c
- tools/interactive-x11.c
- tools/registry-list.c
- tools/xkbcli.c
This is just good practice, but it is also necessary if we want to facilitate the discovery of issues with locales in libxkbcommon.
> tools: Ensure to honor user locale

- src/xkbcomp/symbols.c
Found while working on #680.
Note that we currently display error message suggesting that we recover from errors (e.g. “… ignored”), but we actually do not recover. This MR does not change that.
> symbols: Fix leak in HandleSymbolsDef

- changes/api/+whichGroupState.bugfix.md
- src/text.c
- src/text.h
- src/xkbcomp/keymap-dump.c
This indicator field was previously looked up in the wrong table, resulting the erroneous serialization `(null)`.
> xkbcomp: Fix whichGroupState serialization

- changes/api/692.bugfix.md
- src/registry.c
`libxml2-2.14+` now disallows parsing trailing `NULL` bytes, so don’t. This is backward-compatible with previous versions of the library.
Closes #692.
> registry: Added support for libxml2 2.14+

- .github/workflows/linux.yml
- changes/api/+locale-dependent-floats.bugfix.md
- doc/compatibility.md
- src/xkbcomp/scanner.c
- test/buffercomp.c
- test/common.c
- test/log.c
Before this commit we used `strtold`, which depends on the locale. But the XKB syntax is fixed and use a period as decimal separator. So ensure the syntax is correct without relying on `strtold` and truncate the result.
I encountered this issue parsing a keymap with a geometry which contains floats.
See #681 for an alternative fix.
TODO:
> xkbcomp: Fix parser failure on floats

- changes/api/+extended-rules-wild-cards.feature.md
- doc/compatibility.md
- doc/rules-format.md
- src/xkbcomp/rules.c
- test/data/rules/extended-wild-cards
- test/rules-file.c
Added the following wild cards to the rules file syntax, in addition to the current `*` legacy wild card:
EDIT: *current* proposal:
- `<none>`: Match *empty* value.
- `<some>`: Match *non-empty* value.
- `<any>`: Match *any* (optionally empty) value. Its behavior does not depend on the context, contrary to the legacy wild card `*`.
The verbose wild cards are preferred to single characters:
- More intuitive: self-explanatory.
- Does not steal syntax from other token.
- Extensible syntax, should we need it.
This will enable writing much simpler rules, see [!764] for an example of tricky rules in the `xkeyboard-config` project, that would benefit from the new wild cards. The extended rules support is tracked in [this issue](https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/is …
> rules: Added extended wild cards <none>, <some> and <any>

- changes/api/+replace-include.feature.md
- doc/compatibility.md
- doc/keymap-format-text-v1.md
- doc/rules-format.md
- src/xkbcomp/ast-build.c
- src/xkbcomp/include.c
- src/xkbcomp/include.h
- src/xkbcomp/rules.c
- test/data/rules/merge-mode-replace
- test/rules-file.c
- test/rulescomp.c
Previously only the merge modes “override” and “augment” were available in include statements, using the prefix `+` and `|` respectively. While one can use the `replace` include statement in keymap files, *rules* files have no way to express the *replace* mode.
This commit enables the merge mode “replace” using the prefix `^`. This prefix was chosen because it due to its similarity with the `XOR` bit operator, which convey mutual exclusion.
[Related discussion](https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/issues/525) in `xkeyboard-config` project.
EDIT: changed from `!` to `^` prefix
Other ASCII symbols candidates:
- `!` conveys some kind of higher precedence, akin to CSS `!important`. But it conflicts with the section header `!`, which is a token in the current …
> Enable merge mode “replace” in include statements

- src/keymap-priv.c
- src/keymap.h
- src/state.c
These indexes are fixed, so there is no need to lookup their name.
> keymap: Use constants for Lock and Control indexes

- changes/api/+drop-trailing-empty-actions-and-keysyms.breaking.md
- doc/keymap-format-text-v1.md
- src/xkbcomp/symbols.c
- test/buffercomp.c
- test/data/keymaps/merge-modes/augment.xkb
- test/data/keymaps/merge-modes/default.xkb
- test/data/keymaps/merge-modes/override.xkb
- test/data/keymaps/merge-modes/replace.xkb
- test/data/keymaps/symbols-multi-keysyms-empty.xkb
This brings us closer to what `xkbcomp` outputs. One should use the explicit `VoidSymbol` instead of `NoSymbol`, in order to avoid dropping empty levels.
This may affect keys that rely on an *implicit* key type.
Example:
- Input:
```c
key <> { [a, A, NoSymbol] };
```
- Compilation with xkbcommon \< 1.9.0:
```c
key <> {
type= "FOUR_LEVEL_SEMIALPHABETIC",
[a, A, NoSymbol, NoSymbol]
};
```
- Compilation with xkbcommon ≥ 1.9.0:
```c
key <> {
type= "ALPHABETIC",
[a, A]
};
```
This is also necessary to #699 in order to make `[NoSymbol, NoSymbol]` equivalent to `[{}, {}]`, which simplifies to `[]`.
> xkbcomp: Drop trailing NoSymbol and NoAction()

- changes/api/+empty-keysym-action-lists.feature.md
- doc/keymap-format-text-v1.md
- src/xkbcomp/ast-build.c
- src/xkbcomp/ast-build.h
- src/xkbcomp/parser.y
- src/xkbcomp/symbols.c
- test/buffercomp.c
- test/data/keymaps/symbols-multi-actions.xkb
- test/data/keymaps/symbols-multi-keysyms-empty.xkb
- test/data/keymaps/symbols-multi-keysyms.xkb
Enable empty lists in more places:
- (Empty `interpret`)
- (Empty key `type`)
- (Empty `indicator`)
- Empty list of keysyms and actions: `{}`
Motivations:
- Follow the principle of least astonishment;
- Ensure consistency;
- Enhance the use of custom defaults;
- Facilitate the tests.
Fixes #565
NOTE: Using `{}` for both actions and keysyms introduces an ambiguity, which is resolved when reaching the first non `{}` in the list. I managed to modify the parser the handle it, but I wonder if we can do better.
TODO:
> Support empty symbols and actions lists

- tools/xkbcli-bash-completion.sh
Handle positional argument as a path for the `compile-*` tools.
Fixes #705
> tools: Update bash completion

- bench/custom-parsers.c
- meson.build
- src/keysym.c
- src/scanner-utils.h
- src/utils-numbers.h
- src/xkbcomp/rules.c
- src/xkbcomp/scanner.c
- test/buffercomp.c
- test/data/keymaps/integers.xkb
- test/data/rules/invalid-group-index
- test/data/rules/invalid-group-qualifier
- test/rules-file.c
- test/utils.c
This mainly fixes the case where we would parse a buffer that is not NULL-terminated with the last token being a number. Previously the dummy example:
```c
const char keymap_str[] = {'1'};
```
would trigger a memory violation instead of raising a syntax error and exiting safely.
There are some issues with the rules too.
Note that this is unlikely to be an in issue IRL.
Fixes #690
> Avoid using strto* standard parsers

- changes/api/695.feature.md
- doc/keymap-format-text-v1.md
- src/keymap.c
- src/keymap.h
- src/x11/keymap.c
- src/xkbcomp/compat.c
- src/xkbcomp/keymap-dump.c
- src/xkbcomp/keymap.c
- src/xkbcomp/parser.y
- test/buffercomp.c
- test/data/keymaps/empty-compound-statements.xkb
- test/data/keymaps/stringcomp.data
- test/data/keymaps/symbols-multi-keysyms-empty.xkb
- test/state.c
Before this commit we supported multiple actions per level, but not in *interpret* statements. Let’s fix this asymmetry, so we can equivalently assign all actions sets either implicitly or explicitly.
Fixes #695
> Support multiple actions in interpret

- src/compose/parser.c
- src/xkbcomp/ast-build.h
- src/xkbcomp/compat.c
- src/xkbcomp/keycodes.c
- src/xkbcomp/keymap.c
- src/xkbcomp/parser.y
- src/xkbcomp/symbols.c
- src/xkbcomp/types.c
- src/xkbcomp/xkbcomp-priv.h
Display “(unnamed map)” instead of “(null)”.
> logging: Handle NULL map name

- meson.build
- test/x11.c
- test/x11comp.c
- test/xvfb-wrapper.c
Fixes #709
- meson: Warn if missing xkbcomp for X11 tests;
- test: Better logging to spot missing Xorg executables.
@Apteryks
> build: Warn if missing xkbcomp for X11 tests

- scripts/update-keysyms-derived-headers.py
- src/keysym.c
- src/keysym.h
- src/keysym.h.jinja
- test/keysym.c
Previously there was a distinction between keysyms with code points in BMP and the others: the former used a 4-padding while the latter used a 8-padding: e.g `U0001` vs `U00010000`. This is unnecessary and makes the reading harder.
Let’s use the same padding for all: `U0001` and `U10000`.
Parsing remains unchanged and would parse both paddings.
Also added a test to check no explicit name can clash with Unicode notation.
> keysyms: Pad Unicode keysyms only up to 4 digits

- changes/+keysyms-string.feature.md
- changes/api/+bidi.feature.md
- doc/compatibility.md
- doc/keymap-format-text-v1.md
- meson.build
- src/xkbcomp/ast-build.c
- src/xkbcomp/ast-build.h
- src/xkbcomp/parser.y
- src/xkbcomp/scanner.c
- test/buffercomp.c
- test/data/keymaps/bidi.xkb
- test/data/keymaps/compat-interpret.xkb
- test/data/keymaps/string-as-keysyms.xkb
- test/data/keymaps/symbols-modifier_map.xkb
- test/log.c
Each Unicode code point of the string will be translated to their respective keysym, if possible. When such conversion is not possible, this will raise a syntax error.
This introduces the following syntax:
```c
// Single code point = single keysym
key <1> {["é"]}; // eacute
// String = translate each code point to their respective keysym
key <2> {["sßξك🎺"]}; // {s, ssharp, Greek_xi, Arabic_kaf, U1F3BA}
// Mix string and keysyms
key <3> {[{"ξ", Greek_kappa, "β"}]}; // { Greek_xi, Greek_kappa, Greek_beta}
```
Mixing string and keysyms would allow to mix keysyms with and without Unicode translation[^1].
Implements #636
TODO:
[^1]: Although right now I have no use case in mind. It’s more about the principle of least astonishment: since `"é"` translates to `eacute`, then `{"é", e}` and …
> symbols: Enable writing keysyms list as UTF-8 strings

- bench/rules.c
- meson.build
- src/xkbcomp/rules.c
- test/data/rules/special_indexes
- test/rules-file.c
When using layout index ranges (e.g. special indexes “any” or “later”), the rules still match following the order in the rules file, so layout indexes may match without following their natural order. So the resulting KcCGST value should not be merged with the output until reaching the end of the rule set.
Because the rule set may also involve options, it may match multiple times for the *same* layout index. So these multiple matches should not be merged together either until reaching the end of the rule set.
When reaching the end of the rule set, for each KcCGST component the pending values are then merged: for each layout, for each KcCGST value in the corresponding sequence, merge with the output.
---
Example:
! model = symbols
*     = pc
! layout[any] option = symbols
C           1 …
> rules: Fix merging KcCGST values in layout order

- test/xkeyboard-config-test.py.in
- Enable setting the XKB root directory. By far the most important change.
- Enable to pass registry XML files relative to the target rules directory (with or without the `.XML` extension).
- Enable to set the rules set to use.
- Better JSON/YAML escaping.
- Better error logging.
> test: Improve xkeyboard-config script

- doc/keymap-format-text-v1.md
Just a little thing I noticed -- not all keysyms have a name.
> doc/keymap-format-text-v1: fix inaccurate statement in Keysym glossary entry

- doc/keymap-format-text-v1.md
`LevelThree` and `LevelFive` are mapped respectively to `Mod5` and `Mod3`. This is counter-intuitive but set so for ages and probably hard-coded[^1] in some places.
Thanks to @johnp for indirectly [reporting](https://bugzilla.mozilla.org/show_bug.cgi?id=1827615#c29) via #732. You are not alone to find this situtation confusing 😅
[^1]: Note that this is a bad practice: `LevelThree` → `Mod5` is a *usual* mapping, but no protocol fixes that.
> doc: Fix usual vmods mapping typo

- test/keysym-unicode.c
Fix compilation error when building for Windows with clang-cl:
../subprojects/libxkbcommon-xkbcommon-1.9.0/test/keysym-unicode.c:11:1: error: return type defaults to 'int' [-Wimplicit-int]
../subprojects/libxkbcommon-xkbcommon-1.9.0/test/keysym-unicode.c:11:1: warning: function declaration isn't a prototype [-Wstrict-prototypes]
> test: Fix `main()` function prototype

- README.md
- doc/faq.md
- include/xkbcommon/xkbcommon.h
- meson.build
Apart from the traditional questions:
- Document how to get the vmod → rmod mapping
Some applications may need it to interface with legacy code.
Closes #732
> doc: Introduce a FAQ page with how to get the vmod → rmod mapping

- src/keymap-priv.c
- src/state.c
- test/modifiers.c
When querying for a modifier mapping, we should treat all modifiers equally. So simply store real modifier mapping as we do for the virtual ones.
Also fixed useless boolean conversions.
> Define the mapping of real modifiers explicitly

- changes/api/758.bugfix.md
- src/keymap.h
- src/xkbcomp/keymap.c
- test/data/symbols/latch
- test/state.c
Currently we only ignore key type map entries with non-zero mods and with a zero modifier mask. However, the XKB protocol states ([source]):
> Map entries which specify unbound virtual modifiers are not considered.
So we currently handle `map[Unbound]` key type map entries (all modifiers unbound) but not `map[Bound+Unbound]` entries (mix of bound and unbound modifiers).
Fixed by properly checking unbound modifiers on each key type map entry.
This also fixes a test that was accidentally passing.
Fixes #578
[source]: https://www.x.org/releases/X11R7.7/doc/kbproto/xkbproto.html#:~:text=Map%20entries%20which%20specify%20unbound%20virtual%20modifiers,not%20considered
> Fix key type map entry with unbound vmod not ignored

- changes/api/+no empty compat map.bugfix.md
- changes/api/750.bugfix.md
- src/xkbcomp/keymap-dump.c
- src/xkbcomp/keymap.c
- src/xkbcomp/xkbcomp-priv.h
- test/data/keymaps/bidi.xkb
- test/data/keymaps/compat-interpret.xkb
- test/data/keymaps/empty-compound-statements.xkb
- test/data/keymaps/escape-sequences.xkb
- test/data/keymaps/include-banana-implicit-default.xkb
- test/data/keymaps/include-capslock-custom.xkb
- test/data/keymaps/include-capslock-system.xkb
- test/data/keymaps/include-level3-explicit-default.xkb
- test/data/keymaps/integers-overflow.xkb
- test/data/keymaps/integers.xkb
- test/data/keymaps/keycodes-bounds-multiple-1.xkb
- test/data/keymaps/keycodes-bounds-single-1.xkb
- test/data/keymaps/keycodes-bounds-single-2.xkb
- test/data/keymaps/masks.xkb
- test/data/keymaps/merge-modes/vmods-other-component-direct.xkb
- test/data/keymaps/merge-modes/vmods-same-component-include-default-augment.xkb
- test/data/keymaps/merge-modes/vmods-same-component-include-default-override.xkb
- test/data/keymaps/optional-components-basic.xkb
- test/data/keymaps/optional-components-no-real-led.xkb
- test/data/keymaps/optional-components-none.xkb
- test/data/keymaps/stringcomp.data
- test/data/keymaps/symbols-modifier_map.xkb
- test/data/keymaps/symbols-multi-keysyms-empty.xkb
- test/data/keymaps/unicode-keysyms.xkb
- test/xkeyboard-config-test.py.in
Fixed compat interpretations serialization to meet X11’s xkbcomp requirements:
- interpretations should not be empty
- there should be at least one interpretation
The fixes implied a big bunch of test file updates, thus numerous files modified by this MR.
I compiled all xkeyboard-config before publishing 1.9.0, but I did not check enough X11 compatibility. So this MR also update the xkeyboard-config script to test xkbcommon → xkbcomp chaining on the whole keyboard layout database. I did not detect further errors.
@bluetech @whot This requires a minor release: 1.9.2. I’ll do this tomorrow.
Fixes #750
> Fix compat interpretations serialization

- changes/api/+state-mod-mask-handling.breaking.md
- src/keymap-priv.c
- src/keymap.h
- src/state.c
- src/xkbcomp/keymap.c
- test/modifiers.c
- test/state.c
Currently there are 2 issues with the handling of virtual modifiers in the keyboard state:
1. We assume that the input modifiers masks encode the indexes of all the modifiers of the keymap, but this is true only for the *real* modifiers (at least in xkbcommon and X11). Indeed, since the virtual modifiers *indexes* are implementation-specific, the input modifier masks merely *encode* the modifiers via their *mapping*.
Consider the following keymap:
```c
xkb_keymap {
xkb_compat { virtual_modifiers M1 = 0x100; };
xkb_types  { virtual_modifiers M2 = 0x200; };
};
```
Now to illustrate, consider the following 2 implementation variants of libxkbcommon (assuming indexes 0-7 are the usual real modifiers):
1. Process `xkb_compat` then `xkb_types`. M1 and M2 have the respective indexes 8 and 9 and …
> state: Fix virtual modifiers with non-real mod mapping

- src/xkbcomp/keymap.c
- test/buffercomp.c
- test/data/keymaps/masks-extra-bits.xkb
Since we accept numeric values for the vmod mask in the keymap, we may have extra bits set that encode *no* real/virtual modifier. Keep them unchanged for consistency.
E.g. the following keymap:
```c
xkb_keymap {
xkb_keycodes { <a> = 38; };
xkb_symbols {
virtual_modifiers X = 0xf0000000;
key <a> { [ SetMods(mods = 0x00001100) ] };
};
};
```
would compile to:
```c
xkb_keymap {
xkb_keycodes { <a> = 38; };
xkb_symbols {
virtual_modifiers X = 0xf0000000;
// Internal state
key <a> { [ SetMods(mods = 0xf0001000) ] };
// Serializatiion
key <a> { [ SetMods(mods = 0x00001100) ] };
};
};
```
See also [this discussion](https://github.com/xkbcommon/libxkbcommon/pull/745#issuecomment-2851848503).
TODO:
> Do not discard extra bits in vmod masks

- test/data/compat/basic
- test/data/keymaps/pure-virtual-mods.xkb
- test/data/rules/evdev-pure-virtual-mods
- test/data/symbols/pc
- test/data/types/virtual_modifiers
- test/keyseq.c
- test/modifiers.c
- test/state.c
These tests come from #450, but they work without the new feature of #450 (namely, automatically assigning explicit vmod *canonical* mapping for unmapped vmods), if using explicit virtual mod mappings.
> Add tests for pure virtual modifiers

- PACKAGING
- changes/api/644.feature.rst
- changes/build/644.breaking.rst
- meson.build
- src/xkbcomp/parser.y
- test/log.c
It's not much, but instead of
xkbcommon: ERROR: [XKB-769] (unknown file):5:25: syntax error
we get
xkbcommon: ERROR: [XKB-769] (unknown file):5:25: syntax error, unexpected +, expecting INTEGER
which is at least a little helpful.
> xkbcomp/parser: enable Bison detailed syntax error

- changes/README.md
- changes/api/538.deprecated.md
- include/xkbcommon/xkbcommon-names.h
- towncrier.toml
The following modifiers names in `xkbcommon/xkbcommon-names.h` are now deprecated:
- `XKB_MOD_NAME_ALT`: use `XKB_VMOD_NAME_ALT` instead.
- `XKB_MOD_NAME_LOGO`: use `XKB_VMOD_NAME_SUPER` instead.
- `XKB_MOD_NAME_NUM`: use `XKB_VMOD_NAME_NUM` instead.
Fixes #538
Closes #712
> Deprecate legacy modifiers names

- changes/api/+xkb_keymap_mod_get_mask.feature.md
- doc/faq.md
- include/xkbcommon/xkbcommon.h
- src/keymap.c
- test/modifiers.c
- xkbcommon.map
Added a dedicated API to query modifier masks rather than relying on a hack using `xkb_state_update_mask`. Furthermore, this hack may not work in the future if we remove virtual mods resolution in `xkb_state_update_mask` to avoid corner-cases issues.
Rationale: see [this comment](https://github.com/xkbcommon/libxkbcommon/pull/745#issuecomment-2854029663)
TODO:
> modifiers: Add xkb_keymap_mod_get_mask()

- changes/api/622.feature.md
- doc/keymap-format-text-v1.md
- src/keymap-priv.c
- src/keymap.h
- src/state.c
- src/text.c
- src/xkbcomp/action.c
- src/xkbcomp/keymap-dump.c
- test/buffercomp.c
- test/data/keymaps/symbols-multi-actions.xkb
- test/data/keymaps/voidaction
- test/state.c
Added `VoidAction()` action to match the keysym pair `NoSymbol` / `VoidSymbol`.
It enables erasing a previous action and breaks latches.
This is a libxkbcommon extension. When serializing it will be converted to `LockControls(controls=none,affect=neither)` for backward compatibility. We cannot serialize it to `NoAction()`, as it would be dropped in e.g. the context of multiple actions.
Fixes #622
@mahkoh @Jules-Bertholet
> actions: Add VoidAction(), mirroring NoSymbol/VoidSymbol.

- NEWS.md
- README.md
- doc/Doxyfile.in
- doc/doxygen-extra.css
- doc/license.md
- doc/release-notes.md
- meson.build
- scripts/doxygen-html-fix
- towncrier.toml
Our changelog deserves a better exposition.
Also:
- Added license as well.
- Added a workaround for Doxygen’s limitations on HTML tags. Hopefully this is fixed for good.
- Improved CSS.
> doc: Reformat release notes and include them in the HTML doc

- changes/api/+compose-misoverriding.bugfix.md
- src/compose/parser.c
- test/compose.c
Previously if a new sequence did not produce a keysym or a string, the corresponding property was not overriden, possibly leaking the previous entry.
- Fixed by always writting all the properties.
- Also try to reuse the previous string entry, if possible, so that we avoid allocating.
Discovered while reviewing #570. Probably not an issue in practice if following the standard system Compose file syntax: string + keysym.
> compose: Fix sequence not fully overriden

- changes/api/+compose-new-overrides-old.breaking.md
- include/xkbcommon/xkbcommon-compose.h
- src/compose/parser.c
- test/compose.c
This ensures that it is always possible to override previous definitions, for example when `include`ing the system Compose file.
Fixes #395, as a stopgap while waiting for #398.
> Always retain later Compose sequence in case of conflict

- src/xkbcomp/keymap-dump.c
- test/buffercomp.c
- test/data/keymaps/empty-compound-statements.xkb
- test/data/keymaps/escape-sequences.xkb
- test/data/keymaps/explicit-actions.xkb
- test/data/keymaps/group-index-names-1.xkb
- test/data/keymaps/host.xkb
- test/data/keymaps/include-level3-explicit-default.xkb
- test/data/keymaps/integers.xkb
- test/data/keymaps/masks-extra-bits.xkb
- test/data/keymaps/merge-modes/augment.xkb
- test/data/keymaps/merge-modes/default.xkb
- test/data/keymaps/merge-modes/defaults-include.xkb
- test/data/keymaps/merge-modes/defaults-plain.xkb
- test/data/keymaps/merge-modes/override.xkb
- test/data/keymaps/merge-modes/replace.xkb
- test/data/keymaps/no_void_action
- test/data/keymaps/optional-components-basic.xkb
- test/data/keymaps/stringcomp.data
- test/data/keymaps/symbols-multi-actions.xkb
- test/data/keymaps/symbols-multi-keysyms-empty.xkb
The upcoming raise of the maximum groups count will require to use numeric group indexes instead of the syntax `GroupN` if groups > 8.
Let’s not bother with handling two cases (group count ≤ 8 or > 8) and always serialize group indexes as numeric values.
> dump: Always use numeric group indexes

- src/xkbcomp/rules.c
There was a typo that made parsing hexadecimal instead of the expected decimal format.
Since the bug was shipped in lib versions that supported max 4 groups, there is no impact.
> rules: Fix parsing group index

- src/xkbcomp/keymap-dump.c
Fixed copy-paste error. It worked for now, as both struct have the same first fields, but it is obviously semantically incorrect and not future-proof.
> dump: Fix typo

- changes/api/780.feature.md
- doc/compatibility.md
- doc/keymap-text-format-v1-v2.md
- src/state.c
- src/xkbcomp/action.c
- src/xkbcomp/keymap-dump.c
- test/data/rules/evdev
- test/data/rules/evdev-modern
- test/data/symbols/shift
- test/data/symbols/shift-v2
- test/keyseq.c
It enables e.g. to deactivate `CapsLock` *on press* rather than on release, as in other platforms such as Windows.
It fixes a [18-year old issue] inherited from the X11 ecosystem, by extending the [XKB protocol key actions].
As it is incompatible with X11, this feature is available only using the keymap text format v2.
[18-year old issue]: https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/issues/74
[XKB protocol key actions]: https://www.x.org/releases/current/doc/kbproto/xkbproto.html#Key_Actions
Fixes #780
> keymap: Add option `unlockOnPress` for `SetMods()` and `LatchMods()`

- changes/api/+xkb_utf32_to_keysym-no-deprecated.bugfix.md
- scripts/update-keysyms-names-handling.py
- src/keysym-utf.c
- src/keysym.c
- src/ks_tables.h
- test/keysym.c
Before this commit, some code points could be converted to deprecated keysym. This is incorrect, because the relevant keysyms are all deprecated because their mapping to Unicode is uncertain!
Ensure that `xkb_utf32_to_keysym()` never returns deprecated keysyms, because there is either another non-deprecated keysym or in last resort we always have the correct keysym available in the Unicode keysym range.
> keysym: Do not convert UTF-32 to deprecated keysyms

- changes/tools/+improved-interactive-output.feature.md
- meson.build
- test/common.c
- tools/interactive-evdev.c
- tools/interactive-wayland.c
- tools/interactive-x11.c
- tools/tools-common.c
- tools/tools-common.h
- tools/xkbcli-interactive-evdev.1
- tools/xkbcli-interactive-wayland.1
- tools/xkbcli-interactive-x11.1
Improved the output of events for `xkbcli interactive-*` tools:
- Print key release events. This is particularly useful when analyzing the output sent by another person, in order to know the exact key sequence.
- Print detailed state change events.
- Added `--uniline` to enable uniline event output (default).
- Added `--multiline` to enable multiline event output.
TODO:
> tools: Improve interactive events output

- meson.build
- test/common.c
- test/test.h
- test/utils-text.c
- test/x11comp.c
- test/xvfb-wrapper.c
- test/xvfb-wrapper.h
- More robust call to xkbcomp.
- Enable to test roundtrip with user-provided keymap, e.g. to help designing #858.
Extracted from #591.
> test: Improve Xorg xkbcomp handling

- bench/compile-keymap.c
- changes/api/769.breaking.md
- changes/tools/769.feature.md
- include/xkbcommon/xkbcommon.h
- src/keymap.c
- src/keymap.h
- src/x11/keymap.c
- src/xkbcomp/keymap-dump.c
- src/xkbcomp/keymap.c
- src/xkbcomp/symbols.c
- src/xkbcomp/types.c
- test/buffercomp.c
- test/common.c
- test/data/keymaps/stringcomp-v1-no-flags.xkb
- test/stringcomp.c
- test/test.h
- test/x11comp.c
- tools/compile-keymap.c
- tools/interactive-wayland.c
- tools/interactive-x11.c
- tools/tools-common.h
- tools/xkbcli-compile-keymap.1
- tools/xkbcli-dump-keymap-wayland.1
- tools/xkbcli-dump-keymap-x11.1
When compiling a keymap from text, some items may be unnecessary in the final keymap, i.e. they do not affect the keymap behavior:
- unused key types;
- unused keysym interpretations.
Deactivate the serialization of these items *by default* and add a new flag to enable it for debugging.
Fixes #769
> Keymap: drop unused bits

- changes/build/+default-xkb-root.breaking.md
- meson.build
The *default* XKB root directory is now set from the *most recent* xkeyboard-config installed package, in case [multiple versions] are installed in parallel. It also try to use the package-specific XKB root (if available) rather than the X11 root, respectively defined by the pkg-config variables `xkb_root` (xkeyboard-config ≥ 2.45) and `xkb_base`.
If no such package is found, it fallbacks to the historical X11 directory, as previously.
[multiple versions]: https://xkeyboard-config.freedesktop.org/doc/versioning/
See: related [xkeyboard-config discussion](https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/issues/553) about the v3 format fork.
> build: Enable using default XKB root from recent xkeyboard-config
