xkbcommon/libxkbcommon

configure.ac
src/state.c
src/utils.h
test/common.c
test/interactive-evdev.c
test/interactive-wayland.c
test/interactive-x11.c
test/state.c
test/test.h
xkbcommon.map
xkbcommon/xkbcommon.h

This is an implementation of what I suggested [here](https://bugzilla.gnome.org/show_bug.cgi?id=754110#c30).
There are no tests, so the implementation can have some bug. But I'll add them after we agree on the approach.

Consumed modifiers modes

---

.gitignore
Makefile.am
configure.ac
src/compose/parser.c
src/xkbcomp/expr.c
test/interactive-wayland.c

One small bugfix, and one feature for newer versions of Wayland protocols.

Wayland: xdg-shell v6 support

---

test/interactive-wayland.c

Fixed test for checking failure to create xkb_state in test/interactive-wayland.c

Fixed a minor bug in error detection in Wayland test

---

src/text.c
src/xkbcomp/action.c
src/xkbcomp/ast-build.c
src/xkbcomp/keycodes.c

First two patches are just coverity warnings. Patch 3 is a valid fix but possibly theoretical. Patch4 (FreeStmt) is a definitive bug.

Coverity fixes (one real bug)

---

src/darray.h
src/keymap-priv.c
src/text.c
src/xkbcomp/compat.c
src/xkbcomp/expr.c
src/xkbcomp/parser.y

Most of this was found quite a while ago but got lost.

Fix more fuzz-testing fallout

---

src/xkbcomp/symbols.c

source: https://lgtm.com/projects/g/xkbcommon/libxkbcommon/alerts/?mode=list

Fix some of LGTM warnings

---

.azure-pipelines/steps/dependencies-windows.yml
azure-pipelines.yml
bench/bench.c
meson.build
src/context-priv.c
src/context.c
test/common.c
test/context.c
test/test.h

This is a rebase of #103 on current master, trying to get it to pass CI.

Make it possible to build using Meson and MSVC

---

test/interactive-evdev.c
test/interactive-wayland.c
test/interactive-x11.c

This is what is done in the [guide](https://xkbcommon.org/doc/current/md_doc_quick-guide.html)

 Use flag instead of hardcoded value in evdev examples

---

NEWS
meson.build
xkbcommon.map
xkbcommon/xkbcommon-compose.h
xkbcommon/xkbcommon.h
xkbregistry.map

Bump version to 1.0.0

---

test/tool-option-parsing.py

Fixes https://github.com/xkbcommon/libxkbcommon/issues/185

test: fix the xkbcli --version test

---

src/utils.h
src/xkbcomp/compat.c
test/keysym.c

There are a few more that require investigation, but these are the obvious fixes :)

Scan-build fixes

---

test/tool-option-parsing.py

Add a skipError test function that can analyse rc, stdout, stderr to skip a test
even when we expect an error. We use that to skip if we couldn't find a keyboard
in the interactive-evdev test.
Fixes #235
cc @kachanovskiy

test: allow skipping errors in certain conditions

---

.github/workflows/github-release.yml
.github/workflows/main.yml

- Reduce permissions
- Update some stuff

ci: some tweaks

---

src/x11/keymap.c

In 1b3a1c277a033083fee669e92c8cad862716ebd1 we changed the error
handling in this code to not bail out immediately but only after
everything has been processed, to simplify the code. But I suspect the
code isn't prepared for this and that's what causing the crash reported
in the issue.
Bring back the short-circuit error handling which would hopefully fix
such crashes.
Fixes: https://github.com/xkbcommon/libxkbcommon/issues/252

x11: try to fix crash in xkb_x11_keymap_new_from_device error handling

---

meson.build
meson_options.txt

this is mainly useful for multilib, but may be useful for other users as well
Signed-off-by: Alex Xu (Hello71) <alex_y_xu@yahoo.ca>

build: add enable-tools option

---

include/xkbcommon/xkbcommon.h

Small improvement... more details are in the issue #270

Improve misleading comments #270

---

meson.build
src/context.c
src/utils.h
test/common.c
test/context.c
test/registry.c
test/test.h

Attempt to fix MSVC test compilation issue described in #284.

test: try to fix MSVC

---

meson.build
src/keymap.h
src/text.c
src/xkbcomp/ast.h
src/xkbcomp/symbols.c
test/data/keymaps/modmap-none.xkb
test/filecomp.c
test/modifiers.c

Add support for modmap None.

---

src/registry.c

Found these two 2y old fixes on a branch during spring (well, autumn) clean. Figured I might as well push them :)

registry: two old fixes leftover in my branch

---

.github/workflows/github-release.yml
.github/workflows/linux.yml
.github/workflows/macos.yml
.github/workflows/windows.yml

Mostly to bump to macos one which will hopefully fix CI issues there.

ci: bump runs-on versions

---

NEWS

WIP. The git log will be deleted once relevant info is included.

Update NEWS for 1.6.0

---

meson.build

Fix error message version to match the version check

Update meson.build error message when enable-wayland enabled

---

src/compose/table.c
src/utils.c
src/utils.h
test/compose.c

compose: Ensure we mmap only regular files

---

README.md
doc/cool-uris.yaml
doc/diagrams/xkb-keymap-components.dot
doc/keymap-format-text-v1.md
doc/user-configuration.md
meson.build

WIP this was unpublished since June. Let’s start a PR to remember to finish it!
- Add introduction to keymap and its components
- Add a diagram to explain the relationships between RMLVO and KcCGST.
- Add list of keywords.
- …
Follow-up of #329.

Improve documentation (Part 3)

---

doc/diagrams/xkb-configuration.dot
doc/doxygen-extra.css
doc/introduction-to-xkb.md
doc/keymap-format-text-v1.md
doc/rules-format.md
src/xkbcomp/rules.c

- Improved introduction
- Added examples
- Added RMLVO resolution process

Doc: rules

---

src/darray.h

Fix typo in darray_enumerate_from

---

scripts/perfect_hash.py
scripts/update-unicode.py

Fix types annotations of Python scripts

---

.pre-commit-config.yaml
scripts/perfect_hash.py
scripts/update-message-registry.py
scripts/update-unicode.py

See: https://github.com/astral-sh/ruff/blob/main/CHANGELOG.md#090

scripts: Fix formatting with Ruff 0.9

---

changes/tools/587.bugfix.md
src/registry.c
test/registry.c

xkbcli list: Fix duplicate variants

---

test/data/symbols/level5
test/data/types/complete
test/data/types/extra
test/data/types/level5
test/data/types/numpad

See the corresponding [xkeyboard-config MR](https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/merge_requests/796).

Test:  fix key ypes in data

---

changes/api/579.bugfix.md
src/state.c
test/data/compat/leds
test/state.c

Fix incorrect handling of group indicators

---

src/registry.c

Inline `rxkb_object_unref` for each type and remove the `destroy` field.

registry: Refactor to avoid hazardous casts

---

meson.build
src/xkbcomp/parser.y
test/keysym.c
test/registry.c
test/xvfb-wrapper.c

Small changes fixing a UBSAN error and some compiler warnings.
Sorry for lazily putting it all in a single PR, I can split it if you prefer.

Fix misc compiler warnings

---

src/atom.c
src/compose/parser.c
src/xkbcomp/action.c
src/xkbcomp/compat.c
src/xkbcomp/keymap-dump.c
src/xkbcomp/rules.c

Most notably, the cast for enum *pointers* mentioned in #131.

Fix some issues with implicit int casts

---

.github/workflows/github-release.yml
RELEASING.md

Two things from the 1.8.0 release.

Release fixes

---

src/keysym.h
src/keysym.h.jinja
test/keysym.h.jinja

Accidentally modified generated files in a couple of recent changes. Sync the templates.

Fix a few direct modifications to generated files

---

NEWS.md
changes/api/+group-wrap.bugfix.md
changes/build/628.feature.md
changes/tools/+enable-environment-names.breaking.md
meson.build

- Have write access to xkbcommon Git repositories.
- Be subscribed to the [wayland-devel](https://lists.freedesktop.org/mailman/listinfo/wayland-devel) mailing list.
they have their milestone set to the relevant release and the relevant tag
“critical”.
must be *explicitly* postponed by changing their milestone.
```
Subject: [ANNOUNCE] libxkbcommon MAJOR.MINOR.PATCH
<NEWS & comments for this release>
Git tag:
--------
git tag: xkbcommon-<MAJOR.MINOR.PATCH>
git commit: <git commit sha>
<YOUR NAME>
```
Check carefully that there is no warning during generation with Doxygen.
It may be necessary to use another version of Doxygen to get a clean build.
Building from source using the main branch is also a good option.
- "Our latest API- and ABI-stable release ..."
- Add entry to the `releases` …

Bump version to 1.8.1 and update changelog

---

.github/workflows/linux.yml

This reverts commit 2b3ffb629231e4fc0c94107a2731c20130913c8f.

ci: Revert workaround unavailable gitlab.freedesktop.org

---

changes/api/+optional-keymap-components.feature.md
doc/compatibility.md

Follow-up of #694. For some reason I forgot to sync.

doc: Optional components

---

src/keymap.c
src/keymap.h
src/xkbcomp/symbols.c
test/buffercomp.c
test/data/keymaps/symbols-multi-actions.xkb
test/data/keymaps/symbols-multi-keysyms.xkb

I have these changes in multiple pending MRs, let’s merge it in its own MR and then rebase the MRs to make them smaller and focused.

Miscellaneous minor refactor

---

src/xkbcomp/keycodes.c

Since we now always keep the keycodes array at the minimal dimensions, `max_key_code` is redundant and error prone. Let’s use `darray_size` directly.

xkbcomp: Safer keycode max_key_code

---

src/xkbcomp/symbols.c
test/atom.c
test/compose.c
test/utils.c

Refactor numeric parsers tests

---

src/xkbcomp/ast.h

See [this comment](https://github.com/xkbcommon/libxkbcommon/pull/687#discussion_r2061531246)
@bluetech

ExprKeySym: add comment about error recovery

---

NEWS.md
changes/api/740.bugfix.md
meson.build

- Have write access to xkbcommon Git repositories.
- Be subscribed to the [wayland-devel](https://lists.freedesktop.org/mailman/listinfo/wayland-devel) mailing list.
they have their milestone set to the relevant release and the relevant tag
“critical”.
must be *explicitly* postponed by changing their milestone.
```
Subject: [ANNOUNCE] libxkbcommon MAJOR.MINOR.PATCH
<NEWS & comments for this release>
Git tag:
--------
git tag: xkbcommon-<MAJOR.MINOR.PATCH>
git commit: <git commit sha>
<YOUR NAME>
```
Check carefully that there is no warning during generation with Doxygen.
It may be necessary to use another version of Doxygen to get a clean build.
Building from source using the main branch is also a good option.
- "Our latest API- and ABI-stable release ..."
- Add entry to the `releases` …

Bump version to 1.9.1

---

src/keymap.h
src/state.c
src/xkbcomp/keymap-dump.c
src/xkbcomp/keymap.c

Some updates I started for another MR, that is better to keep separated.

State: minor refactor

---

NEWS.md
changes/api/+no empty compat map.bugfix.md
changes/api/750.bugfix.md
changes/api/758.bugfix.md
meson.build
xkbcommon.map

- Have write access to xkbcommon Git repositories.
- Be subscribed to the [wayland-devel](https://lists.freedesktop.org/mailman/listinfo/wayland-devel) mailing list.
they have their milestone set to the relevant release and the relevant tag
“critical”.
must be *explicitly* postponed by changing their milestone.
```
Subject: [ANNOUNCE] libxkbcommon MAJOR.MINOR.PATCH
<NEWS & comments for this release>
Git tag:
--------
git tag: xkbcommon-<MAJOR.MINOR.PATCH>
git commit: <git commit sha>
<YOUR NAME>
```
Check carefully that there is no warning during generation with Doxygen.
It may be necessary to use another version of Doxygen to get a clean build.
Building from source using the main branch is also a good option.
- "Our latest API- and ABI-stable release ..."
- Add entry to the `releases` …

Bump version to 1.9.2

---

test/state.c

Test group lock wrap.
Motivation: see [this comment](https://github.com/xkbcommon/libxkbcommon/issues/310#issuecomment-2866470533)

test: Added further case to xkb_state_update_latched_locked

---

doc/keymap-format-text-v1.md

- Improve parameters doc of supported actions
- Document some legacy actions

doc: Improve actions

---

doc/keymap-format-text-v1.md

Detailed explanation of:
- modifier declaration
- real/virtual modifier maps
- modifier key binding
- modifier encoding
- modifier portability
Fixes #755
@mahkoh

doc: Modifier declaration and binding

---

src/xkbcomp/rules.c

This provides semantics and better type-check.

rules: Convert macros into enums & inline functions

---

test/rules-file.c
test/state.c

Split into dedicated functions fo better readability.

test: Refactor rules-file and state

---

tools/interactive-wayland.c

Previously a window would appear for a very short time, which is unpleasant and potentially dangerous for people sensitive to flashes.
Fixes #835

tools: Do not use a window for dump-keymap-wayland

---

RELEASING.md

The mailing list has been migrated to Mailman 3.

doc: Update wayland-devel links
